# 影视工程流水线 · 操作手册

> **版本**：1.0（2026-10-07） ｜ **适用版本**：桌面端 ≥ main `8409afa` ｜ **受众**：影视工程功能使用者（第一~十三章）、二次开发者与运维（第十四~十六章）
> **关联文档**：[ARCH-FILM-ENGINEERING-2026-08-14.md](./ARCH-FILM-ENGINEERING-2026-08-14.md)（架构设计 + 全量语料扩展）、[PRD-FILM-ENGINEERING-CANVAS-2026-09-24.md](./PRD-FILM-ENGINEERING-CANVAS-2026-09-24.md)（画布设计）、[PRD-FILM-FULL-CORPUS-PRODUCTION-2026-09-23.md](./PRD-FILM-FULL-CORPUS-PRODUCTION-2026-09-23.md)（全量出片设计）、[openspec/specs/film-engineering/spec.md](../openspec/specs/film-engineering/spec.md)（规范化规格）
>
> **本手册的取证口径**：全部功能点、限制、错误码均以 `main@8409afa` 的实际代码为准，并逐条标注 `文件:行号`。凡规格文档（spec/PRD）与实现不一致的地方，本手册在对应位置显式标注「**规格承诺 / 当前实现**」，不做美化。第十四章集中列出全部已知差异。

---

## 目录

- [一、这是什么](#一这是什么)
- [二、开始之前：四项前置准备](#二开始之前四项前置准备)
- [三、界面地图：两个视图，一个功能](#三界面地图两个视图一个功能)
- [四、核心概念：不懂这七个词后面全看不懂](#四核心概念不懂这七个词后面全看不懂)
- [五、路线 A：浏览与复制提示词（零成本上手）](#五路线-a浏览与复制提示词零成本上手)
- [六、路线 B：剧本一步到分镜](#六路线-b剧本一步到分镜)
- [七、路线 C：画布逐镜出图 / 出片](#七路线-c画布逐镜出图-出片)
- [八、路线 D：经典视图批量出片（≤ 10 镜）](#八路线-d经典视图批量出片-10-镜)
- [九、路线 E：全量分批出片（> 10 镜）](#九路线-e全量分批出片-10-镜)
- [十、路线 F：原片回收（下载原作者成片）](#十路线-f原片回收下载原作者成片)
- [十一、导出：把提示词带到别处](#十一导出把提示词带到别处)
- [十二、成本模型：你会在哪里被拦住](#十二成本模型你会在哪里被拦住)
- [十三、故障排查手册（按症状索引）](#十三故障排查手册按症状索引)
- [十四、限制与已知边界](#十四限制与已知边界)
- [十五、接口速查（给二次开发者）](#十五接口速查给二次开发者)
- [十六、术语表](#十六术语表)
- [附录 A：提示词方法论精读](#附录-a提示词方法论精读)
- [附录 B：三个完整实战案例](#附录-b三个完整实战案例)

---

## 一、这是什么

### 1.1 一句话

**影视工程**是一条「专业影视分镜生产线」：把一部开源 AI 电影的**真实工程方法**（怎么写分镜提示词、怎么锁角色一致性、怎么控制空间与时间）连同**真实分镜数据**打包进应用，让你把自己的剧本套进这套方法里，一键拆成分镜、逐镜出片、合成成片。

页面上副标题原文是：

> 复刻开源 AI 电影《Hell Grind》的完整影视工程：真实分镜提示词、角色/场景/道具资产索引、提示词方法论，支持一键复制与剧本套用。
> —— `apps/desktop/src/locales/zh.js:2518`

### 1.2 它解决什么问题

普通 AI 视频工具的典型困境是：**你写一段描述，模型给你一段不确定的镜头**。同一句提示词跑两次结果不同；角色换个镜头就变脸；空间关系前后颠倒；剪辑点对不上。

影视工程的思路来自真实影视工业：把「怎么拍」拆成**可复用、可粘贴、逐块锁死**的结构化规范。这套规范在应用里体现为一个**提示词块结构**（7 大块，见第四章），每个块解决一个具体问题：

| 提示词块 | 解决的具体问题 |
|---|---|
| `SCENE CONTEXT` 场景上下文 | 角色数量对不上（模型多画/少画人） |
| `GEO SPATIAL LAYOUT` 地理空间布局 | 空间关系前后颠倒（左右互换、越轴） |
| `ACTION TIMING` 动作时间线 | 动作糊成一团、不知道几秒发生什么 |
| `AUDIO` 对白与音效 | 台词跑到画面文字里、音色每镜漂移 |
| `CHARACTER ACTING` 角色表演 | 表演平淡、情绪不连贯 |
| `STYLE` 风格前缀 | 风格逐镜漂移 |
| `POSITIVE CONSTRAINTS` 正向约束 | 细节崩坏（闪烁、多余肢体、质感下降） |

数据实测：随包方法论定义 **7 个块 + 10 条铁律 + 6 条术语**（`apps/desktop/electron/film-kit/prompt-doctrine.json`）。

### 1.3 它不解决什么问题（先说清楚，避免误用）

- **它不是视频剪辑器**。成片是「按顺序把镜头视频拼起来」，没有转场、调色、字幕、音轨处理（`film-render.js:285` 注释明确「无转场/调色/字幕」）。
- **它不是图片生成器为主的功能**。勾选「生成图片」是复用通用图片能力的旁路（上限 20 张），主流是**出视频**。
- **它不训练模型、不微调**。所有提示词都是文本，交给你在模型设置里配好的**默认视频 Provider** 执行。
- **它不保证一次出片成功**。生成走真实视频模型，失败率受 provider 影响；系统提供重试、断点续跑、失败隔离，但**不保证成功**。

### 1.4 能力全景

```
影视工程（film-engineering）
├─ 数据层：film-kit 数据资产（随包精简 / 用户数据全量，两级回退）
│   ├─ 场景树 162 个 · 分镜 153 个（随包）· 资产索引 332 条 · 方法论 7 块 10 律
├─ 引擎层
│   ├─ kit 加载与 schema 校验（fail-closed，绝不部分降级）
│   ├─ 分镜库查询（场景树 / 分镜列表分页 / 分镜详情）
│   ├─ 一键复制文本组装（4 种模式，后端组装保证跨平台一致）
│   ├─ 剧本套用引擎（分场 → 模板映射 → 同构分镜，可选 LLM 润色降级）
│   └─ 提示词导出（JSON / Markdown）
├─ 流水线层：6 阶段执行链（含成本确认 checkpoint）
│   └─ load_template → adapt_script → select_shots → export_prompts → generate_videos → render
├─ 批量层：全量分批出片驱动（切批 / 台账 / 断点续跑 / 失败隔离）
├─ 回收层：原片 resultUrl 下载通道（白名单 + SSRF 防护 + ffprobe 校验）
└─ 交互层
    ├─ 画布视图 /film-engineering（节点连线）
    └─ 经典视图 /film-engineering/classic（三个标签页 + 两个浮层出片面板）
```

---

## 二、开始之前：四项前置准备

### 2.1 准备一：登录状态（许可证门）

**所有会花钱的操作都需要登录态。** 真实 E2E 里有一条明确断言：

> 许可证门 fail-closed（未登录拒绝启动流水线，不静默放行）
> —— `apps/desktop/tests/e2e/film-engineering-real.js:340`

未登录时点「生成」，会得到拒绝错误而不是静默开始消耗额度。

**零成本操作大多不受登录限制**：主进程共注册 16 个 `film-engineering:*` 通道，其中 15 个在「未登录可用」白名单内（`ipc-handlers/license-access-control.js:58-64`），包括浏览场景/分镜、复制、导出、剧本套用、计划预览等。

> ⚠️ **一个例外**：**上传参考图需要登录**。`film-engineering:upload-reference` 是唯一不在白名单里的通道，未登录时会被渲染层许可证守卫拦下，界面提示「参考图上传失败」。这是当前版本的已知策略不一致（同族其余 15 条都允许未登录），详见第十四章。

### 2.2 准备二：模型设置里的默认视频 Provider

这是**最常见的卡点**，请务必先配好。

出视频走的是「模型设置」里配置的**默认视频 Provider**（`video-gen.js:106` 的 `resolveFilmVideoProvider` → `manager.getDefault('video')`）。

> **重要且反直觉的一点**：分镜数据里带的 `model` 字段（比如 `seedance_2_0`）**只用于界面展示，不参与路由**。也就是说，你在分镜详情里看到「模型：seedance_2_0」，实际出片用的是**你配置的默认视频 Provider**。这两者不一致是正常的，不是 bug（`video-gen.js:9` 注释：「kit 分镜的 model 字段仅作展示、不参与路由」）。

未配置时，流水线会以 `VIDEO_MODEL_NOT_CONFIGURED` 失败，界面给出「前往模型设置」按钮。错误文案原文：

> 影视工程视频生成需要视频模型（如 Seedance / Kling / Veo / CogVideo 等），请在模型设置中配置并设为默认视频 Provider 后重试
> —— `video-gen.js:274`

**怎么配**：进入模型设置页 → 添加一个视频 Provider（填 API Key 与端点）→ 把它**设为默认视频 Provider**。保存后回到影视工程页。

### 2.3 准备三：FFmpeg / ffprobe

成片合成阶段（`film_render`）与原片回收下载都依赖 **FFmpeg 和 ffprobe**。合成时会 `findFfmpeg()` / `findFfprobe()` 找可执行文件，找不到就以「FFmpeg 不可用，无法合成成片」失败（`film-render.js:279`、`film-render.js:42`）。

随包精简 kit 的镜头的 `resultUrl` 指向 `*.cloudfront.net` 域名，但**随包 manifest 没有 `allowedHosts` 字段**，因此下载通道会 fail-closed 拒绝（详见第十章与第十四章）。

### 2.4 准备四：磁盘空间与产物目录

产物落在**系统临时目录**下的受控媒体根：

| 平台 | 路径 |
|---|---|
| Windows | `%TEMP%\film-engineering\` |
| macOS | `/var/folders/.../T/film-engineering/` |
| Linux | `/tmp/film-engineering/` |

代码口径：`path.join(os.tmpdir(), 'film-engineering')`（`film-render.js:81`、`video-gen.js:64`）。

目录结构：

```
<mediaRoot>/
├─ <runId>/                     单次 run 的产物目录（runId 由流水线生成）
│   ├─ shot_000.mp4             逐镜视频（序号 = 该镜在本批中的选中序号）
│   ├─ shot_001.mp4
│   ├─ norm_000.mp4             规格不一致时的归一中间产物（仅 normalize 模式）
│   ├─ concat-list.txt          拼接清单
│   └─ final.mp4                成片
├─ references/                  参考图落盘目录
└─ production/<taskId>/
    ├─ ledger.json              出片台账（断点续跑唯一事实源）
    ├─ prod-<taskId>-b0/        第 0 批 run 目录
    └─ recycled/                回收下载的原片
```

> ⚠️ **系统临时目录会被系统清理**。重要成片请用界面上的「打开所在文件夹」/「另存为」导出，或在应用「设置 → 清理」里注意「影视工程缓存」条目（文案原文：「视频合成与影视工程在系统临时目录产生的中间产物，可安全清理以释放磁盘空间」，`zh.js:289`）。

### 2.5 准备检查清单

出第一支片之前，逐条确认：

- [ ] 已登录
- [ ] 模型设置里已配置并**设为默认**的视频 Provider
- [ ] FFmpeg / ffprobe 可用（合成阶段才会用到）
- [ ] 磁盘临时目录有空间（全量出片 144 镜估算约 1.1 GB，见 `ipc-handlers/film-engineering.js:48` 的 `DISK_ESTIMATE_BYTES_PER_SHOT = 8MB`）
- [ ] 已读第四章的七个核心概念

---

## 三、界面地图：两个视图，一个功能

### 3.1 怎么进来

**视频创作页 → 影视工程卡片**。

卡片文案（`zh.js:968` / `zh.js:986`）：

- 名称：`影视工程`
- 描述：`影视工程：复刻《Hell Grind》——真实分镜提示词库、素材索引与剧本套用（一键复制）`

点击后跳转到 `/film-engineering`（`CreateView.vue:1970-1972`）。这是**独立页面路由**，不是就地启动流水线——点卡片只是进入页面，不会自动开始任何生成。

### 3.2 两个视图的分工

| | 画布视图 | 经典视图 |
|---|---|---|
| 路由 | `/film-engineering` | `/film-engineering/classic` |
| 组件 | `FilmCanvasView.vue` | `FilmEngineeringView.vue` |
| 定位 | 节点连线，视觉化编排 | 列表 + 面板，批量与精细操作 |
| 入口 | 视频创作页卡片（默认） | 画布右上角「经典视图」按钮 |
| 适合 | 手上有一份剧本，想看清"哪些镜用了哪些参考图" | 从现成分镜库挑镜头；批量出片；全量出片 |

**建议**：新手从经典视图入门（列表信息密度高、一切都是显式按钮），熟悉后再用画布做创作编排。两者共享同一套后端能力，**功能不互斥**——画布出的成片可以在经典视图查看/导出，反之亦然。

### 3.3 画布视图界面元素

**顶部工具栏**（从左到右）：

| 元素 | 文案原文 | 作用 |
|---|---|---|
| 下拉 1 | 画幅（`16:9 横屏` / `9:16 竖屏` / `跟随原图`） | 全局画幅，影响生成与合成归一 |
| 下拉 2 | 时长（`5 秒` / `8 秒` / `10 秒`） | 全局单镜时长 |
| 按钮 | `拆分镜` | 把上方剧本文本拆成分镜节点 |
| 按钮 | `上传人物参考` | 上传人物参考图 → 生成一个参考节点 |
| 按钮 | `上传场景参考` | 上传场景参考图 → 生成一个参考节点 |
| 主按钮 | `生成所选` | 发起出片（先弹成本确认卡） |
| 按钮 | `清空画布` | 清空所有节点与连线 |
| 链接 | `经典视图` | 跳到经典视图 |

**剧本输入框**：顶部工具栏下方，3 行文本域，占位文案：

> 粘贴剧本正文，按空行分隔场景。点击「拆分镜」自动套用提示词架构生成逐镜节点。

下方一行小字：`剧本最多 10000 字`，以及 `启用 LLM 润色` 复选框。

**画布区**：Vue Flow 底座，自带**背景网格**、**缩放/平移控件**（左下）、**小地图**（右下）。缩放范围 0.3×~2.0×，初始 0.9× 自动适配视图。

**成本确认卡**：点「生成所选」后弹出的对话框，文案：

> 将为 {n} 个分镜生成视频，确认后才开始计费。

按钮：`取消` / `确认成本并生成`。

**成片完成条**：合成成功后画布右下角浮出绿色提示条，含三个入口：`打开所在文件夹` / `另存为` / `前往经典视图查看/导出`。

### 3.4 经典视图界面元素

**三个标签页**（`zh.js` `tabs` 命名空间，实测 `FilmEngineeringView.vue:57/134/184`）：

| 标签 | 文案 | 内容 |
|---|---|---|
| 1 | `分镜库` | 场景树 + 分镜列表 + 工具栏 + 详情抽屉 + 生成结果 |
| 2 | `剧本套用` | 剧本输入 + **角色映射 UI** + LLM 开关 + 结果列表 |
| 3 | `提示词方法论` | 7 大块 + 10 铁律 + 术语表 |

> ⚠️ **别找第四个标签页**。文案表里定义了 `视频生成`（`zh.js` `tabs.video`），但模板里**没有这个 tab-pane**——出片面板是从分镜库工具栏按钮唤起的浮层，不在标签栏上。这是文案定义与实现不一致，不是你操作错了。

另外还有两个**浮层面板**（不在标签页里，由分镜库工具栏按钮唤起）：

- **全量出片面板**（工具栏 `全量出片` 按钮，`data-testid="fe-production-entry"`）
- **视频生成面板**（工具栏 `生成视频` 按钮，`data-testid="fe-video-entry"`）

### 3.5 分镜库标签页详解

**左侧场景树**：按层级组织（实测层级分布：1 个根 + 108 个一级 + 51 个二级 + 2 个三级 = 162 个场景）。场景名如 `1. COLD OPEN`、`assets`。每个场景显示该场景的**素材计数**（实测总和 155,123，对应该片全部素材数）。

**分镜列表**：点场景后加载该场景分镜。显示条：

> 已加载 {loaded} / 共 {total} 镜

超过分页阈值时底部出现「加载更多」按钮。分页契约：单页默认 100、上限 200；不分页时单场景硬上限 500 镜（`shot-library.js:26-28`）。

**工具栏**（分镜列表上方）：

| 按钮 | 文案 | 约束 |
|---|---|---|
| 下拉 | 复制内容（`完整提示词`/`提示词块`/`角色行`/`GEO 布局`） | 选复制模式 |
| 按钮 | `批量复制（N）` | 需先勾选，上限 50 |
| 按钮 | `导出 JSON` | 需先勾选，上限 50 |
| 按钮 | `导出 Markdown` | 需先勾选，上限 50 |
| 主按钮 | `生成图片` | 需先勾选且 ≤ 20 |
| 警示按钮 | `生成视频` | 需先勾选，唤起视频生成面板 |
| 警示按钮 | `全量出片` | 需先勾选，唤起全量出片面板 |

**详情抽屉**：点分镜卡打开。含提示词正文（`.fe-prompt-text`）、模型、分辨率、引用资产缩略图与四个复制按钮（`复制完整提示词`/`复制提示词块`/`复制角色行`/`复制 GEO 布局`），提示词可 `展开全文`/`收起`。

### 3.6 空态与错误态

| 情况 | 界面表现 | 文案原文 |
|---|---|---|
| kit 加载失败 | 画布顶部红色 alert | 标题「影视引擎不可用」+「随包 film-kit 资源缺失或校验失败，请检查安装完整性后重试。」 |
| 非桌面端环境 | 静默降级 | 「当前环境未提供桌面端能力」 |
| 未配置视频模型 | 错误态带跳转按钮 | 「尚未配置默认视频模型…」+ `前往模型设置` |
| 剪贴板不可用 | 降级为可选中文本域 | 「复制失败，请手动选择复制」 |
| 场景无分镜 | 列表空态 | 「该场景暂无分镜」 |
| 未选场景 | 列表空态 | 「请选择左侧场景查看分镜」 |

---

## 四、核心概念：不懂这七个词后面全看不懂

### 4.1 film-kit（数据资产包）

影视工程的全部知识与素材，打包成 4 个 JSON 文件 + 1 个图片目录。存放位置分**两级**：

| 级别 | 位置 | 内容 | 体量 |
|---|---|---|---|
| `userData-full` | 用户数据目录下的 kit 目录 | 全量分镜（导入工具生成） | 大 |
| `asar-bundled` | 应用安装包内 `electron/film-kit/` | 精简代表集 | 随包 |

**加载规则（`kit-loader.js:loadFilmKitChain`）**：

1. 优先尝试 `userData-full`；
2. 目录不存在 → 记为「未导入」，**不算错误、不告警**，继续下一级；
3. 目录存在但**校验失败** → 记入回退列表，并打 `log.warn('[FILM_KIT_FALLBACK] ...')`——**错误可见，不静默**；
4. 全部不可用 → 抛 `FILM_KIT_UNAVAILABLE`，所有查询接口返回该错误。

> **fail-closed 是铁律**：宁可整个功能不可用，也绝不返回「一半场景 + 空分镜」这种半可用状态。校验失败时错误信息里会带**具体文件名与条目索引**（如 `shots[42].prompt 超过上限 50000 字符`），这是给排查用的。

**随包精简 kit 实测数据**（`electron/film-kit/`，可直接核对）：

| 项 | 值 |
|---|---|
| 场景数 | 162（层级：根 1 / 一级 108 / 二级 51 / 三级 2） |
| 分镜数 | 153（**每个分镜各属一个不同场景**，即"每场景取 1 个代表镜"） |
| 资产索引条目 | 332（角色 247 / 道具 64 / 场景 21） |
| 电影时长 | 5706 秒（≈ 95 分钟） |
| 素材总计数 | 155,123 |
| 提示词长度 | 最短 129 字符 / 中位数 15,817 / 最长 39,470（上限 50,000） |
| 模型分布 | seedance_2_0 × 143、nano_banana_2 × 5、soul_cinematic × 3、imagegen_2_0 × 1、cinematic_studio_video_3_5 × 1 |
| 引用图片 | 10 张（`char_1~4.webp` 角色 + `scene_1~6.webp` 场景） |

### 4.2 四个 kit 文件分别管什么

| 文件 | 内容 | 谁在用 |
|---|---|---|
| `film-manifest.json` | 电影元数据（title/durationSec/logline/characters）+ 场景树（id/name/count/parentId/level） | 左侧场景树、状态栏统计 |
| `shot-library.json` | 分镜库：每镜的 shotId / sceneId / prompt / model / refTokens / resultUrl / 宽高 | 分镜列表、复制、出片 |
| `reference-registry.json` | 令牌 → 资产条目（`kind`: character/scene/prop/unknown + name + imageUrls） | 详情抽屉的参考图缩略 |
| `prompt-doctrine.json` | 7 个提示词块 + 10 条铁律 + 6 条术语（中英双语） | 方法论标签页 |

### 4.3 分镜（Shot）与场景（Scene）

- **场景（scene）**：分镜的上层组织单位，有层级（父场景 → 子场景）。例如 `1. COLD OPEN` 是根场景 `Hell Grind` 的一级子场景。
- **分镜（shot）**：最小拍摄单位，一个分镜 = 一个提示词 = 一次生成 = 成片里的一段。

分镜的 `shotId` 是 UUID，`sceneId` 指向所属场景。**校验规则**：任何分镜的 `sceneId` 必须在 manifest 的场景树里存在，否则整个 kit 判定为非法（`kit-loader.js:validateShotSceneRefs`）。

### 4.4 引用令牌 `<<<uuid>>>`

提示词正文里形如 `<<<160c936b-2ca7-4fb6-876b-c3b91b7a87d3>>>` 的片段，就是**引用令牌**——指向 `reference-registry.json` 里的一条资产（某个角色、某个道具、某个场景的参考图）。

三条关键规则：

1. **必须逐字符保留**。复制提示词时令牌原样带出；出片时提示词**原文直送**，不经过任何优化器改写（`video-gen.js:76` 的 `prompt: shot.prompt` 直接赋值）。
2. **格式必须是合法 UUID**。`refTokens` 数组每一项都要通过 UUID 正则校验，否则 kit 判非法（`kit-loader.js:isUuidLike`）。
3. **未知令牌不报错**。解析不到时返回 `{kind: 'unknown'}`，界面显示「未知引用」（`shot-library.js:resolveRef`）。

> **实测分布**：随包 kit 的分镜普遍带 1~2 个引用令牌；剧本套用产生的分镜取模板分镜的前 8 个令牌（`script-adapt.js:156`）。

### 4.5 六大提示词块

除了 `SCENE CONTEXT`（场景上下文）外，方法论里另外六个块在复制与套用时被特殊处理：

| 块 | 复制模式 | 套用时 |
|---|---|---|
| `GEO SPATIAL LAYOUT` | `GEO 布局` 模式只取这一块 | 原样保留 |
| `ACTION TIMING` | 归入 `提示词块` 模式 | 原样保留 |
| `AUDIO` | 归入 `提示词块` 模式 | 原样保留 |
| `CHARACTER ACTING` | 归入 `提示词块` 模式 | 原样保留 |
| `POSITIVE CONSTRAINTS` | 归入 `提示词块` 模式 | 原样保留 |
| `STYLE` | 归入 `提示词块` 模式 | 原样保留（风格前缀逐字粘贴） |

复制时块之间用 `[ 块标题 ]` 分隔，**空块标注「（无）」**（`shot-library.js:buildBlocksText`）。角色描述符（形如 `[CHARACTER: ROKO] ...` 的行）单独成 `角色行` 模式。

### 4.6 流水线、阶段与 checkpoint

影视工程在应用里注册为一条**流水线**（pipeline），有 6 个阶段按序执行（`pipeline-engine.js:480-531`）：

| # | 阶段名 | 类型标识 | 一句话作用 | 需要确认？ |
|---|---|---|---|---|
| 1 | `load_template` | `film_load_template` | 加载 film-kit 模板 | 否 |
| 2 | `adapt_script` | `film_adapt_script` | 剧本分场并套用模板 | 否 |
| 3 | `select_shots` | `film_select_shots` | 过滤出选中分镜 | 否 |
| 4 | `export_prompts` | `film_export_prompts` | 导出提示词集合 | 否 |
| 5 | `generate_videos` | `film_generate_videos` | **逐镜生成视频（花钱）** | **是（成本闸）** |
| 6 | `render` | `film_render` | 合成 `final.mp4` | 否 |

**checkpoint（确认点）**是流水线的暂停机制。第 5 阶段声明了 `checkpointRequired: true` + `checkpointType: 'cost_confirm'`（`pipeline-engine.js:519-520`）：

> 流水线推进到第 5 阶段入口时**先停下**，把成本预估载荷交给界面渲染确认卡。**用户点击确认之前，不会发生任何一次视频 Provider 调用，不产生任何计费。**

这条是硬约束，有三处独立保障：阶段执行器在未确认时提前返回确认载荷（`video-gen.js:281`）、流水线引擎把该返回转成暂停（`pipeline-engine.js` 的 `checkpointRequired` 判定）、E2E 有专门断言「确认前零逐镜成功（成本闸未过不调用 provider）」并检查「成本确认卡含逐镜清单」（`film-engineering-real.js:320`、`325`）。

> **恢复不绕过成本闸**：即使应用在等待确认时退出，重启后恢复该 run 仍会停在同一个确认点（`openspec/specs/film-engineering/spec.md` 成本确认 checkpoint 章节）。

### 4.7 本批、批次、runId、taskId

四个容易混的概念：

| 概念 | 含义 | 取值示例 |
|---|---|---|
| **本批（batch）** | 一次出片里选中的分镜集合，上限 **10 镜** | 选了 5 镜 = 1 批 |
| **runId** | 一次流水线运行的标识，决定产物目录名 | 引擎生成，单批出片用它 |
| **taskId** | 全量出片任务的标识，**你自己起名** | `my-task-01`（只允许字母/数字/`.`/`_`/`-`，长度 1-64） |
| **批次 runId** | 全量出片下每批的 runId，**确定性派生** | `prod-<taskId>-b<批次号>`，如 `prod-my-task-01-b0` |

**为什么批次 runId 要确定性派生**：因为断点续跑靠它定位磁盘产物。如果 runId 随机，重启后就没法知道上次产物落在哪。派生规则写死在 `production-driver.js:55`。

### 4.8 原文直送原则（贯穿全流程）

**影视工程提交给视频 Provider 的提示词，逐字符等于你复制出来的提示词原文。**

这条原则在三处被强制：

1. 阶段执行器直接 `prompt: shot.prompt`（`video-gen.js:77`）；
2. 单镜重试从 run 快照取 `selectedShots[shotIndex].prompt` 逐字提交（`ipc-handlers/film-engineering.js:279-298`）；
3. 全量出片的批执行器先 `getShot(shotId)` 取原文再提交（`production-runner.js:31`）。

**明确不做的事**：不经过 prompt-engine 的视频优化链路的任何环节。规格里写明「对优化器的调用即为本合同违例」。原因很实在——这套提示词已经是结构化的、逐块锁死的，再过一遍通用优化器只会破坏块结构。

---

## 五、路线 A：浏览与复制提示词（零成本上手）

**这条路线一分钱不花、不需要视频模型**，是了解这套方法论最快的方式。推荐第一次使用就从这里开始。

### 5.1 步骤

1. 视频创作页 → 点 `影视工程` 卡片（或先在经典视图里操作）。
2. 切到经典视图的 `分镜库` 标签页。
3. 左侧场景树点任一场景。
4. 右侧出现该场景的分镜卡列表。
5. 点某张分镜卡 → 右侧滑出详情抽屉。
6. 在抽屉里选复制模式，点对应复制按钮。

### 5.2 四种复制模式怎么选

| 模式 | 复制到什么 | 什么时候用 |
|---|---|---|
| `完整提示词` | 提示词全文（含引用令牌、全部块标签） | 喂给任意视频模型；存档 |
| `提示词块` | 按 `[ 块标题 ]` 拆好的结构化文本，空块标「（无）」 | 想研究结构；分块喂给模型 |
| `角色行` | 只保留 `[CHARACTER: ...]` 行 | 锁角色一致性；只改角色不动其他 |
| `GEO 布局` | 只取 `GEO SPATIAL LAYOUT` 块 | 只调空间关系 |

> **为什么复制文本由后端组装**：为了跨平台一致。文本拼装逻辑在主进程（`shot-library.js`），渲染进程只负责写剪贴板。这样 Windows / macOS / Linux 复制出来的内容**逐字符一致**（`ARCH-FILM-ENGINEERING` §4.2）。

### 5.3 批量复制

在分镜列表勾选多个分镜（上限 **50** 个），工具栏点 `批量复制（N）`。合并后的格式：

```
===== [1/5] <sceneId> · <model> =====
<第一个分镜的文本>

===== [2/5] <sceneId> · <model> =====
<第二个分镜的文本>
...
```

### 5.4 复制失败怎么办

剪贴板不可用（权限拒绝 / 环境不支持）时，界面提示：

> 复制失败，请手动选择复制

同时会展示一个可选中的文本域，你手动全选复制即可。**不会静默失败**（`useFilmEngineering.js` 的剪贴板降级逻辑）。

### 5.5 参考资产怎么看

详情抽屉里的「引用资产」区显示 `refTokens` 解析出的缩略图（角色/场景/道具）。点单个令牌可 `复制令牌`。解析不到的显示「未知引用」——这通常意味着令牌在注册表里查不到，属正常降级，不影响出片。

> 参考图 URL 全部强制 **https**，且前端 `<img>` 带 `referrerpolicy="no-referrer"` + 懒加载（安全设计，见架构文档 §8.5）。

---

## 六、路线 B：剧本一步到分镜

**这条路线把「你的剧本」变成「按 Hell Grind 方法组装好的分镜」，仍然不花钱。**

### 6.1 两种入口

- **画布视图**：顶部剧本框 → `拆分镜` 按钮
- **经典视图**：`剧本套用` 标签页 → 填剧本 + 角色映射 → `套用生成`

两者调用的是**同一个后端引擎**，结果同构。画布版会直接把分镜铺成节点。

### 6.2 剧本怎么写才会分场正确

引擎的分场规则（`script-adapt.js:splitScript`）：

1. 先把 `\r\n` 归一为 `\n`；
2. **按空行（连续两个及以上换行）分段**；
3. 识别单行标题的段落，标题模式下匹配：`第X场`、`SCENE n`、`INT.`、`EXT.`、`INT./EXT`（大小写不敏感）；标题会并入**下一段**；
4. 标题行去掉首尾空白；无标题时用该段首行当标题。

**推荐的剧本格式**：

```
第1场 黄昏 废弃工厂

外景。锈蚀的铁门半开，夕阳把影子拉得很长。
ROKO 蹲在墙边，手里攥着一块发烫的石头。

第2场 工厂内部

内景。巨大的齿轮在头顶缓慢转动。
JAXX 从横梁上跳下，落地时扬起一片灰尘。
```

**不推荐**（会导致分场错误）：

```
第一场和第二场都在工厂里，ROKO 一开始在外面，后来进去了，JAXX 也在里面，他们一起看着那块石头发光，然后 ROKO 冲上去，JAXX 拉着他回来……（一整段没有空行）
```

### 6.3 硬性限制

| 限制 | 值 | 越界提示 |
|---|---|---|
| 剧本长度 | ≤ **10,000 字** | `剧本不能超过 10000 字` / `剧本超过 10000 字上限` |
| 剧本非空 | 必须有内容 | `剧本不能为空` |
| 角色映射键数 | ≤ **10** | `角色映射最多 10 个键` |
| 角色映射值 | 每项非空字符串 | `角色映射[ROKO] 必须为非空字符串` |
| 无法分场 | 需有空行分隔 | `剧本无法分场（请用空行分隔场景）` |

> 超限时**不会产生部分分镜**——要么全成功，要么明确报错，不给你半成品（规格明确要求「不产生部分分镜」）。

### 6.4 角色映射怎么填

角色映射把「Hell Grind 的角色」换成「你剧本的角色」。

**默认 4 个槽位**（`useFilmCanvas.js:42`）：`ROKO` / `JAXX` / `LULU` / `REIN`。

这四个名字来自原片主角（`film-manifest.json` 的 `characters`）：

| 槽位 | 描述符原文 |
|---|---|
| ROKO | Determined street kid; crystal arm; glowing red fist when charged. |
| JAXX | Reckless, hungry street kid; always half-joking; London street voice. |
| LULU | Clever street kid; technical voice; flat, fast, precise. |
| REIN | Mysterious street kid; calm under pressure; carries the coordinates. |

**重要：映射是"追加标注"不是"深度替换"。** 引擎会在模板的 `[CHARACTER: ROKO]` 行后面追加 `（你的角色名）`，**保留模板原文**供你后续编辑（`script-adapt.js:buildTemplatePrompt`）。这是刻意的设计——直接替换会破坏模板结构。

例：模板原文
```
[CHARACTER: ROKO] — Tall lean demon figure...
```
映射 ROKO → 老王后
```
[CHARACTER: ROKO]（老王）— Tall lean demon figure...
```

**留空的槽位会被自动剔除**（`useFilmCanvas.js:85-87` 只保留非空值）。你只用 2 个角色就只填 2 个。

> 画布视图**没有角色映射 UI**——它固定用 4 个空槽位，等价于"不做映射"。需要角色映射请到经典视图的 `剧本套用` 标签页。（见第十四章已知差异）

### 6.5 分场与模板是怎么配对的

这是理解套用质量的关键（`script-adapt.js:145`）：

- 引擎把 **kit 里全部分镜按顺序**当作模板池；
- 你的**第 i 场**用 `templates[i % templates.length]`——即**循环取模板**。

**这意味着**：你的场数与 kit 分镜数（153）不匹配时，不同场会套到不同模板上，得到风格各异的提示词。这不是 bug，是"方法复刻、剧情不同"的设计——但**如果你想要风格统一，就得知道这个机制存在**。

**实践建议**：写 3~6 场的剧本，出来的效果最容易把控；写 30 场会得到 30 种不同模板风格的提示词。

### 6.6 套用结果的字段

每个套用分镜与 kit 分镜**同构**（可直接被勾选生成/导出消费）：

| 字段 | 值 |
|---|---|
| `shotId` | `adapt-001`、`adapt-002`…（虚拟 ID，不进 kit） |
| `sceneId` | 由场标题规范化而来（中文保留，非字母数字转 `-`，最长 48 字符）；无标题则 `adapted-scene-001` |
| `prompt` | 按模板块结构组装 |
| `model` | 继承模板分镜的 model |
| `refTokens` | 模板分镜的前 8 个 |
| `roleBindings` | 你的角色映射表 |
| `beatIndex` | 第几场（0 起） |
| `sourceTemplateId` | 用了哪个 kit 分镜当模板 |
| `llmEnhanced` | 是否经过 LLM 润色（默认 `false`） |

### 6.7 LLM 润色：可选项，失败不阻断

**默认关闭**。勾选「启用 LLM 润色」后，引擎会对**前 20 个**分镜逐条调用 LLM 润色提示词（`script-adapt.js:DEFAULT_LLM_BATCH_LIMIT = 20`）。

**失败不阻断**：任何一条润色失败，该条用本地模板结果，其余照常。全部失败时 `llmEnhanced: false`，并给出 warnings。

界面上非阻断提示文案：

> LLM 润色本次未生效，分镜按内置规则架构生成。

经典视图的提示文案：

> 已使用本地模板润色

> **实践建议**：先不开 LLM 跑一遍看基础效果。模板方法本身就是确定性的，LLM 润色可能反而改动块结构。这是我的建议，不是硬性规定——如果你想要更自然的措辞，开着也无妨。

### 6.8 拆分镜会不会花钱

**不会。** 拆分镜阶段**不触发任何计费 Provider 调用**。生成发生在后续显式确认的生成阶段（规格明确要求「拆分镜阶段 MUST NOT 触发任何计费 provider 调用」）。

---

## 七、路线 C：画布逐镜出图 / 出片

### 7.1 完整操作序列

```
进入画布 → 填剧本 → （可选）上传参考图 → 拆分镜 → 选中分镜节点 → 生成所选
   → 成本确认卡 → 确认成本并生成 → 逐镜状态回显 → 成片完成条 → 打开文件夹/另存
```

### 7.2 上传参考图

工具栏两个按钮：`上传人物参考` / `上传场景参考`。

**约束**（`useFilmCanvas.js:121-125` + `reference-store.js`）：

| 项 | 值 | 越界提示 |
|---|---|---|
| 格式 | PNG / JPEG / WEBP | `仅支持 PNG / JPEG / WEBP 图片` |
| 单文件大小 | ≤ **10 MB** | `参考图超过 10MB 上限` |
| 读取失败 | — | `文件读取失败` |

**三道安全防线**（服务端）：

1. **只信文件魔数，不信客户端声明的 MIME**。`sniffImageType` 读文件头字节判断真实类型（PNG `89 50 4E 47`、JPEG `FF D8 FF`、WEBP `RIFF....WEBP`）。
2. **文件名由服务端生成**。用户可控内容（原始文件名）**绝不参与路径构造**，路径穿越在结构上不可能。
3. **落盘目录固定**在受控媒体根的 `references/` 下。

> **参考图不会自动外发**。上传只是落盘成节点，**只有你发起生成时**才随请求提交给 Provider（规格明确要求）。上传本身零成本、零网络。

### 7.3 连线规则（唯一合法的连线）

**只有一种连线合法：参考图节点 → 分镜节点。**

| 上游 | 可连到的下游 |
|---|---|
| 人物参考图 | 分镜 |
| 场景参考图 | 分镜 |
| 剧本节点 | **无**（不能连） |
| 分镜节点 | **无**（不能连） |
| 产物节点 | **无**（不能连） |

来源：`film-canvas-model.js:29-35` 的 `EDGE_RULES` 矩阵。

**四条拒绝原因与对应提示**：

| 拒绝原因 | 界面文案原文 |
|---|---|
| 连到自己 | `不能连接到自身` |
| 重复连线 | `该连线已存在` |
| 节点类型未知 | `未知节点类型` |
| 类型对不合法 | `仅支持「参考图 → 分镜」连线` |

> **连线没有方向语义上的"上游/下游"差异**，是「参考图指向它服务的分镜」。操作上：从参考图节点的连接点拖到分镜节点。

### 7.4 参考图怎么影响生成

连线后，发起生成时系统**自动收集**该分镜所有直连上游的参考图路径，构造 `localReferences` 负载（`film-canvas-model.js:buildLocalReferences`），随生成请求提交（`useFilmCanvas.js:214`）。**你不需要手动上传或复制任何东西。**

**关键限制：不是所有视频 Provider 都支持参考输入。**

`video-reference-inputs.js:26-30` 用**显式映射表**判定能力：

| Provider | 参考参数名 |
|---|---|
| `minimax` | `firstFrameImage` |
| `agnes-video` | `image` |
| `agnes-multimodal` | `image` |
| **其他（含 seedance / kling / veo）** | **不支持** |

> 注释写得很直白：「seedance / kling / veo 等当前 adapter 无参考输入参数，**不得列入**（列入即承诺行为）」。

不支持时的行为：**降级为纯文本出片 + 给出 warning，不静默失败、不阻断**。成本确认卡里会显示「有参考的分镜数 / 当前 Provider 是否支持参考」两项（`video-gen.js:293-296`），**在确认之前你就能看到**。

> **一镜多参考**：v1 只取**第一个有效参考**（首帧语义），后续版本再扩（`video-reference-inputs.js` 头注释）。

### 7.5 生成所选：选中规则

点 `生成所选` 按钮时（`FilmCanvasView.vue:160`）：

- **有选中分镜节点** → 只生成选中的；
- **一个都没选** → 生成**全部**分镜节点。

界面提示（未选任何节点时）：`请先选择要生成的分镜节点`。

**硬上限 10 镜**。超出会被拒绝：

> 单批最多 {max} 个分镜，请减少选择数量

> **注意**：`生成所选` 是"一键全量"入口，很容易一不小心就点了 10 镜。点之前先看看选区。

### 7.6 成本确认卡

点 `生成所选` 后**先弹卡，不花钱**。卡上信息：

> 将为 {n} 个分镜生成视频，确认后才开始计费。

选项（此时可改）：

- 画幅：`16:9 横屏`（默认）/ `9:16 竖屏` / `跟随原图`
- 时长：`5 秒`（默认）/ `8 秒` / `10 秒`

> 画幅与时长也可在**顶部工具栏**提前设定，这里的下拉与顶部同步（`FilmCanvasView.vue` 用的同一个 `chosen` 状态）。

### 7.7 画幅与时长怎么落到请求

| 画幅 | 提交参数 | 说明 |
|---|---|---|
| `16x9` | `width: 1280, height: 720` | 横屏（默认） |
| `9x16` | `width: 720, height: 1280` | 竖屏 |
| `source` | **不下发尺寸** | 跟随 provider 默认输出 |

时长到帧数的映射（`video-gen.js:pickFilmFrameCount`，24 fps）：

| 时长 | 帧数 |
|---|---|
| ≤ 5 秒 | 121 |
| ≤ 8 秒 | 201 |
| ≤ 10 秒 | 241 |

> 提交时**驼峰与下划线两种命名都写**（`numFrames` + `num_frames`），因为不同 provider 的 adapter 读的键不一样（`video-gen.js:78-81`）。

### 7.8 逐镜状态回显

生成过程中，分镜节点状态实时变化（`FilmCanvasView.vue:96-102`）：

| 状态 | 文案原文 |
|---|---|
| 等待 | `待生成` |
| 生成中 | `生成中` |
| 成功 | `已完成` |
| 失败 | `失败` |

**并发度默认 2**（`stage.options.videoConcurrency`，未设时回退 2；`production-runner.js` 的批内并发也是 2）。

### 7.9 失败镜重试

失败的分镜节点上有 `重试` 按钮。点击后：

1. 定位该镜在 run 快照中的序号（找不到就 fail-closed，提示失败）；
2. 复用 `film-engineering:retry-shot` 通道重新提交；
3. **提示词从 run 快照逐字取原文**，不过优化器；
4. 成功后覆盖 `shot_NNN.mp4`。

**重试不改变流水线阶段状态机**——它是一个独立通道，不是阶段回退（规格明确：「单镜重试 MUST NOT 改变流水线阶段状态机」）。

重试失败的提示：`该镜重试失败，请稍后再试或前往经典视图处理`。

### 7.10 成片完成

合成成功后画布右下角浮出绿色条：

- `打开所在文件夹` — 在文件管理器中定位 `final.mp4`
- `另存为` — 另存到你要的位置
- `前往经典视图查看/导出`

> **强烈建议点「另存为」**。产物在系统临时目录，系统清理会删掉（见 2.4）。

### 7.11 画布状态持久化

画布的节点位置、连线拓扑、每节点数据会**自动保存**，重启应用后进入页面自动复原。

| 项 | 实现 |
|---|---|
| 存储位置 | 浏览器 `localStorage`（键 `film-engin…s:v1`） |
| 触发时机 | 拖拽节点结束、拆分镜完成、上传参考图、连线、删除节点 |
| 保存范围 | 节点 id/类型/坐标/白名单字段 + 连线拓扑 + meta（`taskId` / `updatedAt`） |
| schema 版本 | `schemaVersion: 1`，版本不符或结构损坏 → 回落空画布 |

> ⚠️ **三个必须知道的限制**：
> 1. **画布只有一份，全局共享**。没有"新建工程"概念——换一份剧本点「拆分镜」是**追加**节点，不是替换（`useFilmCanvas.js:appendShotNodes`）。想彻底重来要点「清空画布」。
> 2. **镜头状态不持久化**。`setShotStatus` 里没有触发保存，所以刷新后节点状态会回落到上次落盘时的旧值，"失败"节点上的重试按钮可能因此不准。**产物完成态以磁盘实际文件为准**（这是刻意设计——不信任缓存）。
> 3. **剧本正文不持久化**。保存的只有节点与连线，顶部剧本框、LLM 开关、画幅/时长选择刷新后都会重置（`serializeCanvasState` 只序列化 nodes/edges/meta）。

### 7.12 画布上**没有**的功能（重要）

以下功能在规格文档中被提及，但**当前版本没有实现**，别在界面上找：

| 功能 | 状态 | 证据 |
|---|---|---|
| **产物节点**（第 5 类节点） | **未实现**。类型常量已定义（`NODE_TYPES.ARTIFACT`），但全仓无任何创建逻辑。成片改用右下角提示条呈现 | `film-canvas-model.js:20` 定义，全仓无引用 |
| **剧本节点** | **未实现**。`ScriptInputNode.vue` 组件与 3 个文案键已就绪，但全仓无代码创建 `scriptInput` 节点 | `film-canvas-model.js:16` + `FilmCanvasView.vue:183`，无创建点 |
| **撤销 / 重做** | **未实现**。工具栏无按钮、代码无逻辑、无相关依赖 | 全仓画布相关文件 grep `undo`/`redo` 零命中 |
| **自动布局按钮** | **未实现**。只有拆分镜时的一次性网格铺布（每行 4 个） | 无 `autoLayout`/`dagre` 依赖 |
| **删除连线** | **未实现**。只能删节点（会级联删掉相关连线），无法单独删一条线 | 无 `removeEdge`，模板无边插槽 |
| **画布空态引导** | **未实现**。空画布只有点阵网格，无任何提示文案 | `canvas.*` 命名空间无空态文案键 |
| **「已注入 N 张参考」** | **永不显示**。该提示依赖 `data.refCount`，而全仓无任何代码写入该字段 | `ShotNode.vue:46` 是唯一引用点 |
| **整段 run 失败提示** | **未实现**。`phase === 'failed'` / `'cancelled'` 没有渲染分支，模板只渲染「等待确认」与「完成」 | `FilmCanvasView.vue:43,211` |
| **Provider 未配置引导** | **无专用文案与按钮**。画布把所有非特定错误泛化为「影视引擎不可用」；**经典视图**才有「前往模型设置」 | `FilmCanvasView.vue:113-115` |
| **画布角色映射 UI** | **未实现**。composable 里有 4 个预置槽位但画布无输入框，实际恒传空映射 | `useFilmCanvas.js:42,85-87` |

已实现的画布交互：拖拽移动、连线、删除节点、缩放（0.3×~2×）、平移、小地图导航、背景网格、初始自动适配视图。详见第十四章。

---

## 八、路线 D：经典视图批量出片（≤ 10 镜）

比画布更适合"从现成分镜库挑镜头"。

### 8.1 步骤

1. 经典视图 → `分镜库` 标签页
2. 左侧选场景，右侧勾选要出的分镜（**上限 10 镜**）
3. 工具栏点 `生成视频`（唤起视频生成面板）
4. 面板里选画幅与时长 → 点 `发起生成`
5. **成本确认卡**出现 → 看逐镜清单 → `确认生成` / `取消`
6. 逐镜状态回显（`待生成` / `生成中` / `成功` / `失败`）
7. 失败镜点 `重试`
8. 全部完成 → 成片完成态 → `打开所在文件夹` / `另存为` / `再来一批`

### 8.2 成本确认卡上能看到什么

经典视图的确认卡比画布详细（`zh.js` `video.confirmHint`）：

> 将为 {totalShots} 个分镜生成视频（画幅 {aspect} / 时长 {seconds}s，Provider：{provider}）。确认后才开始计费生成。

并附**逐镜清单**（每行：镜序号 + shotId + 标题 + 画幅 + 时长）。这份清单来自引擎的 `costCheck` 载荷（`video-gen.js:286-304`）。

> **确认前零调用**。E2E 有专门断言：`确认前零逐镜成功（成本闸未过不调用 provider）`，`successBeforeConfirm === 0`（`film-engineering-real.js:320`）。

### 8.3 状态与文案对照

| 状态 | 文案原文 | 附加操作 |
|---|---|---|
| 待生成 | `待生成` | — |
| 生成中 | `生成中…` | — |
| 成功 | `成功` | — |
| 失败 | `失败` | `重试` 按钮 |
| 成片完成 | `成片已生成` | `打开所在文件夹` / `另存为` / `再来一批` |
| 生成失败 | `生成失败` | `前往模型设置`（仅 `VIDEO_MODEL_NOT_CONFIGURED` 时） |
| 已取消 | `已取消` | `再来一批` |

> `再来一批` 按钮的作用是**重置本次 run 状态**（`useFilmVideoGen.js:249` 把 `phase` 置回 `idle`），不是自动再跑一批。

### 8.4 一批镜的产物规则

**产物命名绑定选中序号，不是分镜 ID**：

```
shot_000.mp4   ← 本批第 1 个选中分镜
shot_001.mp4   ← 本批第 2 个
...
```

序号从 **0** 起。合成阶段按这个序号顺序拼接（`film-render.js:collectDiskShots`）。

> **这就是单镜重试能工作的原因**：重试第 3 镜就是覆盖 `shot_002.mp4`（界面显示的第 3 镜 = 序号 2），合成时按序号对齐，不会错位。

### 8.5 部分失败怎么办

**部分失败不阻断整批。** 5 镜里 1 镜失败，其余 4 镜产物正常落盘，阶段结果标记为「部分成功」（`partialFailure: true`），失败镜在结果清单里标注原因并可单独重试。

**全部镜失败**才让阶段失败（`video-gen.js:367-369`），错误信息会拼上每一镜的失败原因。

### 8.6 单镜失败的失败原因分类

系统保证**失败时一定留痕**，不只是成功才记日志（`video-gen.js:154-160`）。可辨识的失败类别：

| 类别 | 触发条件 | 日志/清单文案 |
|---|---|---|
| 提交被拒 | Provider 返回非零 code | `视频生成调用失败（provider: X）` |
| Provider 返回错误 | 内层 `data.code < 0` | `视频生成失败（provider: X）` |
| 未返回任务 ID | 响应里没有 taskId | `视频生成未返回任务 ID（provider: X）` |
| 轮询超时 | 超过 10 分钟没拿到 URL | `视频生成超时或失败（provider: X）` |
| 下载/异常 | 下载失败、抛异常 | 具体异常信息 |

**运维无需重跑即可从日志读取失败类别**——日志里带镜头序号、shotId 与原因（`log.warn('FilmVideoGen', 'shot N (shotId) failed: reason')`）。

### 8.7 单批轮询的硬参数

| 参数 | 值 | 代码位置 |
|---|---|---|
| 轮询间隔 | 10 秒 | `video-gen.js:44` |
| 轮询上限 | 10 分钟 | `video-gen.js:45` |
| 并发度 | 默认 2 | `video-gen.js:320-321` |
| 单批上限 | 10 镜 | `video-gen.js:39` |
| 帧率 | 24 fps | `video-gen.js:43` |

> **10 分钟轮询上限是硬超时**。慢 Provider 上单镜超过 10 分钟会被判超时失败。若你的 Provider 排队较久，考虑减少单批镜数或换 Provider。

---

## 九、路线 E：全量分批出片（> 10 镜）

当选中的分镜**超过 10 个**，单批装不下时用这条路线。系统自动切批、逐批确认、断点续跑。

### 9.1 什么时候该用

| 场景 | 路线 |
|---|---|
| ≤ 10 镜 | 路线 D（经典视图视频生成面板） |
| > 10 镜 | 路线 E（全量出片面板） |
| 几百镜、要回收原作者成片 | 路线 E + 路线 F（先回收再精修） |

> 全量 kit 有 6558 镜（若已导入）。全部出片按每镜 8MB 磁盘估算约 **52 GB**，按每镜 300 秒墙钟估算约 **23 天**——**这不是一个能随手点的操作**，务必先看计划预览。

### 9.2 步骤

1. 经典视图 → `分镜库` → 勾选要出的分镜（**上限 1000 镜**）
2. 工具栏点 `全量出片`
3. 填 **任务 ID**（占位文案：`用于出片台账与断点续跑，如 my-task-01（仅限字母/数字/._-）`）
4. 点 `发起出片` → 出现 **批次计划预览**
5. 读计划（批数、磁盘预估、耗时预估）→ 点 `确认执行本批`
6. **逐批重复**：每批一个确认卡 → `确认执行本批` → 等这批跑完 → 下一批
7. 全部批次收口 → 出现 `合成成片` 按钮 → 点它 → 等待合成
8. 成片完成 → `打开所在文件夹` / `另存为`

### 9.3 任务 ID 规则

| 项 | 规则 | 违规提示 |
|---|---|---|
| 字符集 | 字母、数字、`.`、`_`、`-` | — |
| 长度 | 1~64 | `任务 ID 只允许字母、数字、._-，长度 1-64` |
| 路径安全 | 不能含路径分隔符（`taskId === path.basename(taskId)`） | — |

**为什么要自己起 taskId**：它是台账文件名与批次 runId 的来源（`prod-<taskId>-b0`）。**重启后靠它找回进度**。起名建议带日期，如 `hellgrind-batch-01-20261007`。

### 9.4 计划预览怎么看

点 `发起出片` 后展示（`ipc-handlers/film-engineering.js:382-395`）：

| 字段 | 文案原文 | 计算口径 |
|---|---|---|
| 批次摘要 | `共 {batches} 批（每批最多 {size} 镜），本次 {shots} 个分镜` | 镜数 ÷ 10 向上取整 |
| 磁盘预估 | `磁盘预估` | 镜数 × 8 MB |
| 耗时预估 | `耗时预估` | 镜数 × 300 秒（换算成 `{n} 分钟`） |
| 媒体目录 | `媒体目录` | 受控媒体根绝对路径 |

> **计划预览是纯只读的，零 Provider 调用、零计费**（规格明确）。

### 9.5 逐批确认（D9 语义）

**每批都要单独确认一次**。这是刻意的设计——你可以在跑完前几批后随时停手，不至于一次确认就烧掉几十镜的额度。

确认卡文案：

> 第 {i}/{n} 批 · {count} 个分镜 · 画幅 {aspect} · 时长 {seconds}s
>
> 确认后才开始本批生成；确认前零模型调用、零计费。

还有一条**累计预算**提示：

> 累计已确认 {count} 镜

帮助你在多批推进中掌握总花费。

### 9.6 切批规则

- 批大小固定 **10**（`PRODUCTION_BATCH_SIZE`）
- **保序切分**：严格按勾选顺序，不打乱
- 批次 runId 确定性派生：`prod-<taskId>-b<批次号>`

**例子**：144 镜 → 15 批（14×10 + 1×4）。第 0 批 = 第 1~10 镜，第 1 批 = 第 11~20 镜，…，第 14 批 = 第 141~144 镜。

### 9.7 断点续跑：磁盘说了算

**这是全量出片最重要的设计**。

断点续跑的唯一裁决依据是**磁盘上有没有产物文件**，不是台账里写的状态（`production-driver.js:resolveResumePlan`）：

| 台账记录 | 磁盘复核结果 | 处理 |
|---|---|---|
| `done` | 文件齐 | 跳过，**零 Provider 调用** |
| `done` | 文件缺 | **降级重跑**（不信台账） |
| `pending` | 文件齐 | 复核通过，**跳过** |
| `failed` | 文件齐 | 复核通过，**跳过** |
| 任意 | 文件缺 | 执行本批 |

**具体做法**：应用在第 8 批进行中崩溃/被关掉 → 重启后输入同一个 taskId → 点 `恢复任务` → 前 7 批被跳过（不花钱），从第 8 批未完成的镜继续。

> **台账是"批/镜两层状态"的 JSON**，每镜条目持久化 `error` 字段（无失败时为空），所以重启后仍能读到上次失败原因，**不用重跑归因**。

台账路径：`<mediaRoot>/production/<taskId>/ledger.json`。

### 9.8 恢复任务（只读视图）

`恢复任务` 按钮调 `production-status` 通道：

- **纯只读、零 Provider 调用、零计费**
- 读台账 + 磁盘双核，返回每批每镜状态
- 无台账时提示：`未找到该任务的出片台账，请确认任务 ID 或先发起一次出片`

> ⚠️ **注意**：恢复视图需要你**同时提供 taskId 和当初那批 shotIds**（`validateProductionArgs` 要求两者都在）。只输 taskId 不行——系统需要 shotIds 才能重建批次结构。

### 9.9 失败隔离

**一批失败不影响其他批。**

- 单批内某镜失败 → 记入台账该镜 `error`，批次标记 `failed`，**继续下一批**
- 批收口后以磁盘复核为准（不信执行器自报）
- 全部批次收口时，若仍有缺失镜头 → **不产出成片**，返回 `暂无法合成：渲染清单未收口（{error}）`

> 也就是说：**缺镜时不会给你一个"少了几段的假成片"**。这是硬设计（`film-render.js:250-257` fail-closed）。

### 9.10 收口与合成

全部批次 `done` 且磁盘复核全过后，系统**自动生成渲染清单**（`renderManifest`）：

```
[{ shotId, path, sourceKind: 'generated'|'downloaded', orderIndex }, ...]
```

`orderIndex` 从 0 连续、不重复，**可跨批次 run 目录**。清单上限 **10,000 条**。

界面提示：`全部批次已收口，渲染清单共 {count} 条`，同时出现 `合成成片` 按钮。

点 `合成成片` 走一个**独立的收口 run**：该 run 没有 selectedShots 但带 renderManifest，六个阶段前四个直通，`generate_videos` 阶段**显式声明 `checkpoint: false`**（零计费直通，不弹成本卡），直接进 `film_render` 跨 run 聚合合成。

### 9.11 合成规则（两条路径共用）

| 片段情况 | 合成方式 | 结果 |
|---|---|---|
| 全部片段**编解码规格一致** | concat demuxer + `-c copy` **零重编码直拷** | 快、无损 |
| 规格**不一致** | 仅做**最小 scale+pad 归一**后再直拷 | 统一画幅，不加转场/调色/字幕/音轨处理 |

规格比较包含：编码格式、宽、高、帧率、时基、**有无音轨**、采样率、声道数（`film-render.js:specKey`）。

归一目标画幅：16x9 → 1280×720，9x16 → 720×1280，source → 首个片段宽高。归一参数：libx264 / veryfast / crf 23 / aac / 24fps（`film-render.js:286-293`）。

> **规格不一致是有可能的**：不同批次可能用了不同 Provider 或不同模型。归一是自动的，不用你干预，但**会重编码**（耗时 + 有损）。

### 9.12 渲染清单的安全校验

`renderManifest` 每一项都要过四道校验（`film-render.js:parseRenderManifest`）：

| 校验 | 拒绝条件 |
|---|---|
| 结构 | 必须为对象，`shotId` 非空字符串 |
| 序号 | `orderIndex` 为非负整数、不重复、**从 0 连续** |
| 来源 | `sourceKind` 必须是 `generated` 或 `downloaded` |
| 路径 | 绝对路径 + `realpath` 规范化后**必须位于受控媒体根内**（拒绝 `..` 遍历、symlink/junction 逃逸） |
| 存在 | 文件必须真实存在 |

任一不通过 → **fail-closed**，不读取该路径、不产出成片，并列出非法条目。

### 9.13 全量出片的进度事件

批执行时通过 `film-engineering:production-update` 事件推送进度（`production-driver.js`）：

| 事件 | 含义 |
|---|---|
| `production:batch` | 批次级：`running` / `done` / `failed` / `skipped-complete` |
| `production:shot-progress` | 逐镜级，**500ms 节流**合并 |
| `production:complete` | 全部结束，回报 `ok` / `doneCount` / `totalCount` / `failedBatchCount` |

> **节流负载只带计数与索引，不带 shotIds 数组**——这是 IPC 负载守卫，防止几百镜时事件把渲染进程打爆（`production-driver.js:18-19`）。

---

## 十、路线 F：原片回收（下载原作者成片）

**每个 kit 分镜都带原作者生成的成片 URL（`resultUrl`）**。随包 kit 实测 153 镜**全部**有 `resultUrl`。

这条路线让你把原作者的成片下载到本地，作为素材精修，**不花一分钱**。

### 10.1 界面入口

全量出片面板里的引导文案：

> 建议先回收原片到本地再精修：远端结果链接有效期有限，过期后需重新生成。

按钮：`回收全部原片` → 状态 `回收中…` → 完成显示 `已回收 {ok}/{total} 个文件到 {dir}`。

### 10.2 分片机制

- **单次上限 50 个文件**（`MAX_RECYCLE_BATCH`）
- 超 50 个自动分片，串行发起
- **并发上限 4**（`RECYCLE_CONCURRENCY`）

### 10.3 落盘位置

```
<mediaRoot>/production/<taskId>/recycled/shot_NNN.mp4
```

落盘后即成为 `renderManifest` 中 `sourceKind: 'downloaded'` 的条目，**可直接参与合成**。

### 10.4 安全合同（全部 fail-closed）

这是整条链路安全要求最严的部分（`shot-downloader.js`）：

| 防线 | 规则 |
|---|---|
| 协议 | **仅 https**，http 直接拒绝 |
| 主机白名单 | 必须与 kit manifest 的 `allowedHosts` **精确匹配**（禁通配、禁子域后缀） |
| 内网黑名单 | 即使塞进白名单，回环/内网/链路本地地址仍拒绝（SSRF 防护，覆盖 IPv4/IPv6 与映射地址） |
| DNS 复核 | 每次请求（含 3xx 每一跳）**发起前先解析 DNS 并校验 IP**——主机名判断不是唯一防线 |
| 跳转 | 3xx **手动逐跳跟随**，每跳重新过白名单 + DNS 校验，最多 3 跳（防环） |
| 大小 | 单文件上限 **500 MB**，流超限立即中止 |
| 完整性 | 写 `.part` 临时文件 → **ffprobe 验证通过才 rename** 为正式片段 |
| 清理 | 任何失败路径清理 `.part`，不留半成品 |
| 目录 | 落盘目录必须在受控媒体根内 |

> **没有自动预取**。下载动作必须**用户显式触发**，浏览/查询分镜时不会偷偷下载（规格明确要求）。

### 10.5 ⚠️ 随包 kit 目前无法回收

**实测：随包精简 kit 的 `film-manifest.json` 没有 `allowedHosts` 字段**（值为 `None`）。

而 `validateDownloadUrl` 的第一条规则就是：

```js
if (!Array.isArray(allowedHosts) || allowedHosts.length === 0) {
  return { ok: false, reason: 'allowedHosts 清单缺失，拒绝下载（fail-closed）' }
}
```
—— `shot-downloader.js:55-57`

`getAllowedHosts()` 在字段缺失时返回空数组（`film-engineering-service.js:105`）。

**结论：使用随包 kit 时，「回收原片」会全部失败**，每镜报「主机名不在 allowedHosts 精确清单内」或「allowedHosts 清单缺失」。这是**设计上的 fail-closed**（宁可不下载，也不放开任意 URL 下载），不是 bug。

**要使用回收功能，需要导入全量 kit**（全量 kit 的 manifest 带 `allowedHosts` 白名单）。参见 14.2。

### 10.6 回收失败怎么办

单镜失败**不中断批次**，每项独立返回成功/失败：

| 情况 | 结果 |
|---|---|
| URL 过期（404） | 该镜标记下载不可用，**媒体目录不留半成品**，可逐镜转入生成路径 |
| 返回非视频内容 | ffprobe 校验失败，拒绝 rename，不留坏片段 |
| 无 `resultUrl` | 提示「该镜无 resultUrl，无法回收下载（需走批量出片重新生成）」 |
| 文件超 500MB | 拒绝，清理 `.part` |

> 全部失败的镜会进入 `renderManifest` 的缺镜清单，导致合成 fail-closed。**必须逐镜处理完（或明确放弃）才能合成**。

---

## 十一、导出：把提示词带到别处

### 11.1 两种格式

在分镜库勾选分镜（**上限 50**）后，工具栏两个按钮：

**导出 JSON** —— 结构化，适合喂给脚本或工具：

```json
[
  {
    "shotId": "1b9f0ff0-1fe6-4fe6-9747-67c4ce7edf80",
    "sceneId": "2f0e48fe-1bfb-46e2-b88d-443da2ee8f90",
    "prompt": "EXACT 2 CHARACTERS\n\n<<<160c936b-...>>> [img_soroh] — ...",
    "model": "seedance_2_0",
    "refTokens": ["160c936b-...", "421b50fd-..."]
  }
]
```

**导出 Markdown** —— 适合人读与贴笔记，每镜一段：

```text
## [1] 2f0e48fe-1bfb-46e2-b88d-443da2ee8f90 · seedance_2_0

EXACT 2 CHARACTERS
...
```

### 11.2 文件名

```
film-engineering-prompts-YYYY-MM-DD.json
film-engineering-prompts-YYYY-MM-DD.md
```

按导出当天的日期命名（`film-engineering-stages.js:227`）。

### 11.3 校验规则

| 项 | 规则 | 越界提示 |
|---|---|---|
| 分镜数 | 1~50 | `selectedShots 必须为 1-50 项的数组` |
| 每镜 prompt | 非空且 ≤ 50000 字符 | `selectedShots 每项必须含非空 prompt（<=50000 字符）` |

> 随包 kit 的分镜 prompt **中位数就有 15,817 字符，最长 39,470**——都在上限内，但如果你手工粘贴超长提示词，会被拒。

### 11.4 ⚠️ 一个静默行为

导出时传的 `format` 参数**只有 `'markdown'` 会命中**，**其他任何值（包括拼错的 `'md'`）都会静默回落成 JSON**，不报错（`ipc-handlers/film-engineering.js:207`）。

界面按钮是写死的两个，走界面不会踩到这个坑；但**写脚本调 IPC 时要注意**——你以为导出了 Markdown，实际拿到的是 JSON。

---

## 十二、成本模型：你会在哪里被拦住

### 12.1 哪些操作花钱

| 操作 | 花钱？ | 说明 |
|---|---|---|
| 浏览场景/分镜/方法论 | ❌ | 纯本地数据 |
| 复制提示词（四模式） | ❌ | 纯文本组装 |
| 导出 JSON / Markdown | ❌ | 纯文本组装 |
| 剧本套用 / 拆分镜 | ❌ | 纯本地模板引擎 |
| 上传参考图 | ❌ | 只落盘，不外发 |
| 计划预览 / 恢复任务 | ❌ | 只读，零 Provider 调用 |
| **生成图片**（≤20 镜） | ✅ | 调图片 Provider |
| **生成视频**（≤10 镜/批） | ✅ | 调视频 Provider |
| **全量出片** | ✅ | 按批，逐批确认 |
| 回收原片 | ❌ | 只是下载，不调生成 |

### 12.2 三道成本闸

**第一道：单批上限。** 一次最多 10 镜。超过直接拒绝，**不启动流水线**。

**第二道：成本确认 checkpoint。** 第 5 阶段入口强制暂停，展示逐镜清单，用户显式确认后才产生任何调用。三处独立保障 + E2E 断言（见 4.6）。

**第三道：全量出片逐批确认。** 每一批都要单独确认，界面显示「累计已确认 N 镜」。

### 12.3 恢复路径也不绕过

**这是最容易误解的一点**：应用在等待确认时崩溃/退出，重启后恢复该 run，**仍然停在同一个确认点**。没有绕过路径（规格明确要求）。

同理，全量出片重启后，已完成批次被跳过（**不花钱**），未完成批次仍需重新确认。

### 12.4 成本估算口径

计划预览给出的估算（`ipc-handlers/film-engineering.js:48-49`）：

| 项 | 口径 | 依据 |
|---|---|---|
| 磁盘 | 镜数 × **8 MB** | POC 实测单镜 4.5~8.5 MB，取上限 |
| 墙钟 | 镜数 × **300 秒** | 并发 2、单镜均值约 10 分钟 |

**这只是量级参考，不是报价。** 真实费用取决于你配的 Provider 定价。

参考量级：

| 规模 | 批次 | 磁盘估算 | 墙钟估算 |
|---|---|---|---|
| 10 镜 | 1 | 80 MB | 50 分钟 |
| 50 镜 | 5 | 400 MB | 4 小时 10 分 |
| 144 镜 | 15 | 1.15 GB | 12 小时 |
| 1000 镜（上限） | 100 | 8 GB | 83 小时 |

### 12.5 成本相关的错误码

| 错误 | 触发 | 怎么办 |
|---|---|---|
| `VIDEO_MODEL_NOT_CONFIGURED` | 未配置默认视频 Provider | 去模型设置配置并设为默认 |
| `tooManyShots` | 单批超 10 镜 | 减少选择数量，或用全量出片 |
| 许可证门拒绝 | 未登录启动流水线 | 登录 |

---

## 十三、故障排查手册（按症状索引）

### 13.1 页面进不去 / 功能整体不可用

**症状**：画布顶部红色告警「影视引擎不可用 / 随包 film-kit 资源缺失或校验失败，请检查安装完整性后重试。」，所有按钮变灰。

**原因**：两级 kit 都不可用。这是 **fail-closed** 设计的正常表现。

**排查步骤**：

1. **看具体错误**。经典视图的错误卡片会显示 `status.error` 原文，里面带**文件名与条目索引**，例如：
   - `film-manifest.json: manifest.filmMeta.title 必须为非空字符串`
   - `shot-library.json: shots[42].prompt 超过上限 50000 字符`
   - `shot-library.json: shots[17].refTokens 含非法 token`
   - `shot-library.json: shots[8].sceneId 指向不存在的场景: xxx`
2. **判断是缺文件还是校验失败**：
   - `xxx.json 缺失或不可读` → 安装包不完整，重装应用
   - `xxx.json JSON 解析失败` → 文件损坏，重装应用
   - `xxx: <具体 schema 错误>` → 内容非法，通常是 kit 被外部改过
3. **看是不是回退了**。如果你导入过全量 kit 但它损坏，系统会回退到随包精简 kit 并打 `[FILM_KIT_FALLBACK]` 日志——**此时功能仍可用**，只是数据变少了。可在经典视图头部看 `kitSource` 字段（`userData-full` / `asar-bundled`）。

**不要做的事**：不要去改 `electron/film-kit/` 下的 JSON——它在 asar 安装包内，改了会被覆盖，且任何 schema 违规都会导致整个功能不可用。

### 13.2 「生成视频」点了没反应 / 报「影视引擎不可用」

**症状**：画布点「生成所选」，弹出错误「影视引擎不可用」。

**注意**：画布的报错文案是**泛化的**——任何非「超镜数」「未选镜」的失败都显示这一条（`FilmCanvasView.vue:113-115`）。所以**这句话不代表真的 kit 坏了**。

**最可能的真实原因**：没配视频模型。

**怎么办**：
1. 去**模型设置**配一个视频 Provider 并**设为默认**；
2. 回到**经典视图**重试——经典视图的出片面板有专门的错误提示和「前往模型设置」按钮，画布没有；
3. 若经典视图明确报「尚未配置默认视频模型…」，那就是这个原因。

### 13.3 「单批最多 10 个分镜」

**症状**：点生成被拒。

**原因**：单批硬上限 10 镜。

**怎么办**：
- 减到 10 镜以内，分多次出（每次成片单独保存）；或
- 用**全量出片**（经典视图 → 分镜库 → 勾选 → 全量出片），系统自动切批。

> 画布的「生成所选」在**没选中任何节点时会生成全部**，很容易一不小心就超 10 镜。点之前先看选区。

### 13.4 剧本套用失败

| 提示 | 原因 | 怎么办 |
|---|---|---|
| `剧本不能为空` | 剧本框是空的 | 填内容 |
| `剧本超过 10000 字上限` | 超长 | 拆成多次，或精简 |
| `拆分镜失败，请重试` | IPC 失败或异常 | 重试；持续失败看日志 |
| `剧本无法分场（请用空行分隔场景）` | 没有空行 | 按 6.2 的格式加空行 |

> `剧本无法分场` 只在**经典视图**显示。画布的报错是泛化的 `拆分镜失败，请重试`。

### 13.5 画布「生成所选」后节点全变失败，但没有错误提示

**症状**：点生成后，分镜节点徽标全变「失败」，但画布上没有任何错误说明。

**原因**：画布**没有整段 run 失败的 UI**——模板只渲染了「等待确认」和「完成」两种状态（`FilmCanvasView.vue:43`、`:211`），`failed` / `cancelled` 状态**没有渲染分支**。

**怎么办**：切到**经典视图**看具体错误。经典视图的出片面板有完整的失败态（错误原因 + 「前往模型设置」按钮）。

### 13.6 合成阶段失败

| 错误 | 原因 | 怎么办 |
|---|---|---|
| `FFmpeg 不可用，无法合成成片` | 找不到 ffmpeg | 安装 FFmpeg 并确保在 PATH |
| `ffprobe 不可用，无法探测片段规格` | 找不到 ffprobe | 同上 |
| `film_render 缺失镜头产物，无法合成成片（缺失镜序号: N, M）` | 有镜没生成成功 | 对这些序号**逐镜重试**补齐后再合成 |
| `film_render renderManifest 校验失败：…` | 清单有非法条目 | 看具体原因：越界路径 / 序号不连续 / 重复 |
| `暂无法合成：渲染清单未收口（…）` | 还有批次没完成 | 先把所有批次跑完或处理掉失败镜 |

> **「缺镜不出片」是硬设计**。系统宁可失败也不给你一个少了几段的假成片（`film-render.js:250-257`）。

### 13.7 单镜一直失败

**症状**：同一镜重试多次都失败。

**排查**：

1. **看失败原因**。清单里会标注，可辨识类别见 8.6。常见：
   - `视频生成未返回任务 ID` → Provider 返回格式变了，或 Provider 不支持这个调用方式
   - `视频生成超时或失败`（10 分钟）→ Provider 排队太久或任务卡住
   - `视频生成调用失败（provider: X）` → API Key 失效、额度不足、限流
2. **换 Provider 测试**。把默认视频 Provider 换成别的，单独出这一镜。
3. **看应用日志**。失败会打 `[FilmVideoGen] shot N (shotId) failed: 原因`——**不需要重跑就能读**。

### 13.8 全量出片恢复不了

**症状**：点「恢复任务」提示「未找到该任务的出片台账」。

**排查**：

| 检查 | 说明 |
|---|---|
| taskId 是否输错 | 区分大小写；必须与当初完全一致 |
| **是否同时提供了 shotIds** | 恢复需要 taskId **+ 当初那批 shotIds**，只输 taskId 不行 |
| 台账是否还在 | 路径 `<mediaRoot>/production/<taskId>/ledger.json`；临时目录被系统清理会丢 |
| shotIds 顺序是否变了 | 批次结构不一致时系统会重建台账（等于从头开始） |

### 13.9 回收原片全部失败

**症状**：点「回收全部原片」，全部报错。

**最可能的原因**：**你在用随包 kit**。随包 manifest 没有 `allowedHosts` 字段，下载通道 fail-closed 全拒（见 10.5）。

**其他可能**：

| 原因 | 表现 |
|---|---|
| URL 过期（404） | 该镜标记下载不可用 |
| 文件超 500MB | 拒绝 |
| 非视频内容 | ffprobe 校验失败 |

### 13.10 参考图上传失败

| 提示 | 原因 |
|---|---|
| `仅支持 PNG / JPEG / WEBP 图片` | 格式不对（GIF/BMP/HEIC 都不行） |
| `参考图超过 10MB 上限` | 太大 |
| `文件读取失败` | 文件读不出 |
| `参考图上传失败`（笼统） | **可能是未登录**——上传参考图需要登录（见 2.1） |

### 13.11 画布节点乱了 / 想重来

**症状**：节点位置乱、混了多个剧本的分镜。

**原因**：画布**只有一份，全局共享**（见 7.11），换剧本点「拆分镜」是追加不是替换。

**怎么办**：点工具栏「清空画布」。**没有二次确认**，直接清空且不可撤销（撤销功能未实现）。

> ⚠️ 清空前确认你要留的东西已经另存。清空会同时删掉 localStorage 里的画布状态。

### 13.12 找不到「撤销」按钮

**没有这个功能。** 画布的撤销/重做/自动布局/边删除**均未实现**（见 7.12、第十四章）。误删节点只能手动重新拆分镜。

### 13.13 成片找不到了

产物在**系统临时目录**，系统清理会删。

**预防**：每次成片后立刻点「另存为」。

**找回**：检查清理记录，或看应用「设置 → 清理」里的「影视工程缓存」条目（该条目清理后不可恢复）。

---

## 十四、限制与已知边界

本章集中列出**规格文档承诺与当前实现不一致**的地方，以及实测确认的硬限制。全部经代码核实，标注了取证位置。

### 14.1 画布功能缺口

| 功能 | 规格承诺 | 当前实现 | 证据 |
|---|---|---|---|
| **产物节点**（第 5 类节点） | spec 要求画布承载 5 类节点 | **未实现**。类型常量 `NODE_TYPES.ARTIFACT` 已定义，但**全仓无创建逻辑、无渲染插槽**。成片以右下角提示条代替（openspec `tasks.md:9` 早已声明「独立产物节点后置」） | `film-canvas-model.js:20`；`FilmCanvasView.vue:183-194` 只有 4 个插槽 |
| **剧本节点** | spec 列为 5 类之一 | **未实现**。`ScriptInputNode.vue` 组件与 3 个文案键已就绪，但**无任何代码创建 `scriptInput` 节点** | `film-canvas-model.js:16` + `FilmCanvasView.vue:183`，全仓无创建点 |
| **撤销 / 重做** | spec「支持撤销/重做」 | **未实现**。工具栏无按钮，代码零逻辑，无相关依赖 | 全仓 `FilmCanvasView.vue`/`useFilmCanvas.js`/`film-canvas-model.js`/节点组件 grep `undo\|redo` 零命中 |
| **自动布局** | spec「支持自动布局」 | **未实现**。只有拆分镜时一次性网格铺点（每行 4 个），无 dagre/elk 依赖、无按钮 | `film-canvas-model.js:56,64-93` |
| **边删除 UI** | — | **未实现**。只能删节点（级联删边），无法单独删一条连线 | `FilmCanvasView.vue:181-199` 无边插槽；`useFilmCanvas.js` 只暴露 `removeNodes` |
| **画布空态引导** | — | **无**。空画布只有点阵网格，无任何提示文案 | `FilmCanvasView.vue:181-199`；`canvas.*` 命名空间无空态键 |
| **「已注入 N 张参考」** | — | **死 UI**。依赖 `data.refCount`，但**全仓无任何代码写入该字段**，永不显示 | `ShotNode.vue:46` 是唯一引用点 |
| **整段 run 失败提示** | — | **无**。`phase === 'failed'` / `'cancelled'` 没有渲染分支，模板只渲染 `awaiting-confirm` 与 `done` | `FilmCanvasView.vue:43,211` |
| **画布内 provider 引导** | spec「引导用户到模型设置页」 | **无专用文案与按钮**。画布把所有非特定错误泛化为「影视引擎不可用」；**经典视图**才有「前往模型设置」 | `FilmCanvasView.vue:113-115` vs `FilmEngineeringView.vue:348` |
| **画布角色映射** | spec 起始面板含角色映射 | **无 UI**。composable 有 4 个预置槽位但画布无输入框，实际恒传空对象 | `useFilmCanvas.js:42,85-87`；`FilmCanvasView.vue:167-176` 无相关控件 |

### 14.2 数据与 kit 限制

| 限制 | 实情 | 证据 |
|---|---|---|
| **随包 kit 无 `allowedHosts`** | 导致「回收原片」在随包 kit 下**全部 fail-closed** | `film-manifest.json` 无该字段；`shot-downloader.js:55-57` 首条即拒空清单 |
| **随包 kit 分镜分布** | 153 镜**各属不同场景**（每场景 1 个代表镜），不是均匀分布 | 实测 `shot-library.json` distinct sceneId = 153 |
| **随包 kit 无 L1 扩展字段** | 153 镜**全部没有** `durationSec`/`aspectRatio`/`iterationCount`/`adoptedJobAt` | 实测字段并集只有 9 个键 |
| **`thumbnailUrl` 不对外暴露** | 数据里有该字段，但 `ShotLibrary._toPublic` 不返回它，**前端永远拿不到缩略图 URL** | `shot-library.js:_toPublic` 返回 8 个字段，不含 `thumbnailUrl` |
| **全量 kit 不在仓库** | 6558 镜全量 kit 由导入工具生成，不进仓库（数十 GB） | `ARCH-FILM-ENGINEERING` §3.3、§9.4 |
| **全量出片上限 1000 镜** | 超出拒绝 | `ipc-handlers/film-engineering.js:46` |

### 14.3 权限与策略不一致

| 项 | 实情 |
|---|---|
| **上传参考图需登录** | 16 个通道中**唯一**不在「未登录可用」白名单的通道（渲染层 `PUBLIC_METHODS` 同样漏了它，只列了 15 个方法）。而 `requiredLevelForMethod` 对未列方法默认 `'authenticated'` → 未登录时 preload 直接抛「许可证权限不足，无法调用 uploadReference」，界面显示「参考图上传失败」 |

### 14.4 流水线元数据三处不一致

同一个「影视工程」流水线，**三处定义的阶段数与成本档各不相同**：

| 来源 | 阶段数 | 阶段名 | 成本档 |
|---|---|---|---|
| 主进程 `pipeline-engine.js:480-531`（**执行权威**） | **6** | load_template / adapt_script / select_shots / export_prompts / generate_videos / render | **high** |
| 渲染侧 i18n `pipeline-labels.js:92-97` | **4** | browse / select / copy / adapt（且**这 4 个 key 没有中文翻译**） | — |
| 卡片常量 `pipeline-constants.js:32-34` + `create-view-module-utils.js:243-245` | **4** | — | **low** |

**你实际看到的是卡片常量（4 阶段 / low）**——因为 `withVideoCloneEntry` 会先过滤掉主进程下发的 `film-engineering`，再把硬编码条目 splice 回去（`create-view-module-utils.js:248,251`）。

**以主进程 6 阶段为准。** 本手册第四章 4.6 节的六阶段表是执行真相。

### 14.5 已知代码瑕疵（不影响使用，供维护者参考）

| 瑕疵 | 实情 | 位置 |
|---|---|---|
| `batchIndex` 上界复用了「镜数」常量 | 文案「必须为 0-999 的整数」与守卫 `batchIndex >= 1000` **自洽，无文案错误**。真实瑕疵是**常量语义复用**：`MAX_PRODUCTION_SHOTS`（镜数上限，用于校验 `shotIds.length`）被当作 batchIndex 上界，而 batchIndex 的合理上界应是批数 `⌈shotIds.length/10⌉`。结果是可用超大下标越界查询（查不到批次，返回空批次视图，不致错但语义松） | `ipc-handlers/film-engineering.js:46,67,404-407` |
| `export` 的 `format` 静默回落 | 非法 format 值不报错，静默按 JSON 处理 | `ipc-handlers/film-engineering.js:207` |
| `production-plan` 的 taskId 被硬编码 | 传 `taskId: 'plan'` 绕过路径安全校验（该通道本就不接收真实 taskId） | `ipc-handlers/film-engineering.js:384` |
| 画布 STORAGE_KEY 含 Unicode 省略号 | 键名是 `film-engin…s:v1`（含 U+2026），不是 `film-engineering-canvas:v1`。排查看数据时别猜 | `useFilmCanvas.js:24`（`od -c` 验证字节 `E2 80 A6`） |
| 画布持久化是 localStorage 非「工程文件」 | 代码注释与 openspec 任务描述写的是「userData 工程文件」，实现是浏览器 localStorage | `useFilmCanvas.js:32,218` |
| 镜头状态不持久化 | `setShotStatus` 内无 `persist()` 调用，刷新后状态回落到落盘时的旧值 | `useFilmCanvas.js:199-202` |
| 剧本正文/LLM 开关/画幅时长不持久化 | `serializeCanvasState` 只序列化 nodes/edges/meta | `film-canvas-model.js:169-187` |
| 经典视图无 LLM 降级提示 | `adaptScript` 返回的 `llmEnhanced` 被丢弃，勾了 LLM 但没生效时**无任何提示**（画布有提示） | `useFilmEngineering.js:424-429` |
| 「视频生成」标签页文案定义但未使用 | `tabs.video` 有文案，模板无对应 tab-pane | `zh.js` `tabs.video` vs `FilmEngineeringView.vue:57,134,184` |
| 经典视图「复制令牌」不走降级 | 直接用 `navigator.clipboard.writeText` 且 catch 静默，非安全上下文下点了没反应也无反馈 | `FilmEngineeringView.vue:668-674` |
| `retry-shot` 未纳入 sender 校验测试清单 | 契约测试的 CHANNELS 数组（15 条）逐条断言 `-3`，但**不含该通道**（由另一个测试文件单独覆盖） | `ipc-handlers/film-engineering.test.js:75-91` |
| 真实 provider 冒烟脚本断言过期 | 断言点击入口后是 `.film-engineering-view`，但 `/film-engineering` 实际渲染 `.film-canvas-view`（`router/index.js:52`）。**跑该脚本前需先修** | `tests/e2e/film-video-provider-smoke.js:229` |

### 14.6 设计上的硬约束（不是缺陷，别试图绕过）

| 约束 | 原因 |
|---|---|
| kit 坏了整个功能不可用 | fail-closed：宁可不可用也不返回半套数据 |
| 缺镜不产出成片 | 避免"少几段的假成片" |
| 未配置视频 Provider 直接失败 | 不静默回退到别的 Provider |
| 提示词原文直送，不过优化器 | 通用优化器会破坏块结构 |
| 下载白名单精确匹配 | SSRF 防护，不接受通配 |
| 断点续跑信磁盘不信台账 | 台账可能与磁盘不一致（崩溃在写盘前） |
| 成本闸在第 5 阶段入口 | 前四阶段零计费，可以放心预演 |

---

## 十五、接口速查（给二次开发者）

> 本章面向要在应用里嵌入或自动化这条流水线的人。用户可跳过。

### 15.1 preload API 面

`window.electronAPI.filmEngineering.*`（`electron/preload/film-engineering.js:14-32`）。**共 16 个 invoke 方法 + 1 个事件订阅**。

**统一返回信封**：`{ code, data?, message?, errorCode? }`，`code === 0` 为成功。

```js
// 典型用法
const fe = window.electronAPI.filmEngineering
const st = await fe.status()                    // 永不失败：恒 code 0，available 可能为 false
const scenes = await fe.listScenes()            // [{id,name,count,parentId,level,shotCount}]
const page = await fe.listShots(sceneId, { limit: 100, offset: 0 })  // {shots,total,limit,offset}
const detail = await fe.getShot(shotId)         // public shot + resolvedRefs[]
const txt = await fe.copyText(shotId, 'blocks') // {text, mode}
const adapt = await fe.adaptScript({ script, characterMap, llmEnabled })  // {adaptedShots, llmEnhanced, warnings}
const exp = await fe.exportPrompts(shots, 'markdown')  // {export:{json,markdown}, fileName}
const vid = await fe.generateSelected(shots, { aspectRatio: '16:9' })  // {results, partialFailure}
const ref = await fe.uploadReference({ dataUrl: 'data:image/png;base64,...' })  // {path,fileName,bytes,mime}
const rt  = await fe.retryShot({ runId, shotIndex, aspect, seconds })
const dl  = await fe.downloadRecycled({ taskId, items: [{shotId, orderIndex}] })
const plan = await fe.productionPlan({ shotIds })
const run  = await fe.productionRunBatch({ taskId, shotIds, batchIndex, aspect, seconds })
const stt  = await fe.productionStatus({ taskId, shotIds })
const off  = fe.onProductionUpdate(cb)         // 返回退订函数
```

### 15.2 参数上限速查

| 通道 | 上限 |
|---|---|
| `adapt-script` | script ≤ 10000 字符；characterMap ≤ 10 键、值非空 |
| `export` / `copy-texts` | 数组 ≤ 50；每项 prompt 非空且 ≤ 50000 字符 |
| `generate-selected` | 数组 ≤ 20 |
| `retry-shot` | shotIndex 为非负整数且 < run 的 selectedShots 长度 |
| `download-recycled` | items ≤ 50；orderIndex 为 0~9999 整数且不重复 |
| `production-plan` / `run-batch` / `status` | shotIds 1~1000；taskId 路径安全；batchIndex ≥ 0 |
| `upload-reference` | 解码后 ≤ 10 MiB；仅 PNG/JPEG/WEBP（**按魔数判定，不信客户端 MIME**） |

### 15.3 错误码

**数值码**（`electron/core/error-codes.js`）。本功能实际只产生 4 个：

| 码 | 含义 | 何时出现 |
|---|---|---|
| `0` | SUCCESS | — |
| `-1` | REQUEST_ERROR | 业务失败、kit 不可用、Provider 未配置 |
| `-2` | VALIDATION_ERROR | 入参不合法 |
| `-3` | AUTH_ERROR | sender 校验失败（`withSenderCheck`）或许可证门 |

**字符串码**：

| 字面量 | 载体 | 含义 |
|---|---|---|
| `FILM_KIT_UNAVAILABLE` | **message 前缀**（不占 `errorCode` 字段） | 两级 kit 均不可用，message 聚合各级具体原因 |
| `VIDEO_MODEL_NOT_CONFIGURED` | `errorCode` 字段 | 未配置默认视频 Provider |
| `FILM_KIT_FALLBACK` | **仅日志**，非 IPC 码 | 某级 kit 损坏回退下一级 |

> `FILM_KIT_UNAVAILABLE` **不带 `errorCode` 字段**，只作为 `message` 的前缀出现。判断 kit 状态应该用 `status` 通道的 `data.available`，不要靠解析 message。

### 15.4 安全边界

| 层 | 机制 |
|---|---|
| IPC 入口 | 16/16 通道包 `withSenderCheck`，拒绝非受信窗口（`app://localhost` / 安装目录内 `file://` / 开发态 localhost） |
| 载荷 | 渲染端必须提交**纯 JSON**（Vue 响应式代理会触发 structuredClone 失败）——各 composable 用 `cloneJson()` 脱壳 |
| 参考图 | 魔数嗅探 + 服务端生成文件名 + 受控根落盘 + 10 MiB 上限 |
| 下载 | https-only + `allowedHosts` 精确匹配 + DNS 公网复核 + 3xx 逐跳复检 + ffprobe 校验 + 500 MB 上限 |
| 渲染清单 | realpath 规范化后必须位于受控媒体根内（拒绝 `..` 遍历与 symlink 逃逸） |
| taskId | 必须满足 `taskId === path.basename(taskId)` |
| 台账 | `.tmp` + rename 原子写，崩溃不留半截 JSON |

### 15.5 关键常量集中表

| 常量 | 值 | 位置 |
|---|---|---|
| `FILM_PROMPT_MAX_LEN` | 50000 | `kit-loader.js:21` |
| `MAX_SCRIPT_LENGTH` | 10000 | `script-adapt.js:13` |
| `MAX_CHARACTER_MAP_KEYS` | 10 | `script-adapt.js:14` |
| `DEFAULT_LLM_BATCH_LIMIT` | 20 | `script-adapt.js:15` |
| `FULL_LOAD_LIMIT` / `MAX_PAGE_LIMIT` / `DEFAULT_PAGE_LIMIT` | 500 / 200 / 100 | `shot-library.js:26-28` |
| `MAX_VIDEO_BATCH` | 10 | `video-gen.js:39` |
| `FILM_ASPECTS` / `FILM_DURATIONS` / `DEFAULT_FILM_SECONDS` | `['16x9','9x16','source']` / `[5,8,10]` / 5 | `video-gen.js:40-42` |
| `POLL_INTERVAL_MS` / `POLL_DEADLINE_MS` | 10s / 10min | `video-gen.js:44-45` |
| `PRODUCTION_BATCH_SIZE` | 10 | `production-driver.js:29` |
| `PRODUCTION_BATCH_CONCURRENCY` | 2 | `production-runner.js:13` |
| `EVENT_MERGE_MS` | 500 | `production-driver.js:30` |
| `RENDER_MANIFEST_MAX` | 10000 | `film-render.js:91` |
| `MAX_DOWNLOAD_BYTES` / `MAX_REDIRECTS` | 500 MB / 3 | `shot-downloader.js:30,32` |
| `MAX_REF_BYTES` | 10 MiB | `reference-store.js:17` |
| `MAX_GENERATE_BATCH` | 20 | `film-engineering-service.js:23` |
| `MAX_RECYCLE_BATCH` / `RECYCLE_CONCURRENCY` | 50 / 4 | `ipc-handlers/film-engineering.js:44-45` |
| `MAX_PRODUCTION_SHOTS` | 1000 | `ipc-handlers/film-engineering.js:46` |

### 15.6 受控媒体根布局

```
path.join(os.tmpdir(), 'film-engineering')
├─ <runId>/shot_NNN.mp4 | norm_NNN.mp4 | concat-list.txt | final.mp4
├─ references/                （参考图落盘）
└─ production/<taskId>/
   ├─ ledger.json
   ├─ prod-<taskId>-b<N>/shot_NNN.mp4
   └─ recycled/shot_NNN.mp4
```

> `os.tmpdir()` 在 Windows 是 `%TEMP%`、macOS 是 `/var/folders/.../T/`、Linux 是 `/tmp/`。**会被系统清理**。

### 15.7 端到端测试

| 脚本 | 跑法 | 性质 |
|---|---|---|
| `pnpm test:e2e:film-engineering`（`tests/e2e/film-engineering-real.js`） | 打包 exe + Playwright 驱动 | **默认进 CI**，不产生真实计费（未登录 profile 走许可证门分支） |
| `tests/e2e/film-video-provider-smoke.js` | 需 `FILM_SMOKE_OPT_IN=1` + 已登录 profile + 已配视频模型 + ffprobe | **opt-in、真实计费、不进 CI**。⚠️ `:229` 的断言已过期，跑前先修（见 14.5） |

真实 E2E 覆盖的 25 个用户操作序列见 `apps/desktop/tests/e2e/film-engineering-real.js:153-350`，包括成本闸不变式断言（`:319-320` 确认前逐镜成功数必须为 0）。

### 15.8 数据资产重建

全量 kit 由导入工具生成（不进仓库）：

```bash
python scripts/film-engineering/fetch-hell-grind-kit.py \
  --source-dir <全量语料目录> --out-dir <kit 目录> \
  --full --dry-run          # 先对账
```

关键口径：分镜按 `created_at` 最大的 completed **视频** job 采纳；提示词中的 `<<<uuid>>>` 与 `params.reference_elements[].id` 匹配（**不是 job id**）；`FILM_PROMPT_MAX_LEN` 与 JS 侧同值 50000；落盘走 `.tmp` → rename 原子写。

---

## 十六、术语表

| 术语 | 英文 / 标识 | 含义 |
|---|---|---|
| 影视工程 | film-engineering | 本功能名。流水线 id = `film-engineering`，页面 `/film-engineering` |
| 场景 | scene | 分镜的上层组织单位，有层级（parentId/level） |
| 分镜 | shot | 最小拍摄单位 = 一个提示词 = 一次生成 = 成片一段 |
| 引用令牌 | reference token / `<<<uuid>>>` | 提示词里指向参考资产的 UUID 片段，**必须逐字符保留** |
| 资产索引 | reference-registry | 令牌 → 资产条目（character/scene/prop/unknown + 图 URL） |
| film-kit | — | 数据资产包：manifest + shot-library + reference-registry + prompt-doctrine + images |
| 场景上下文 | SCENE CONTEXT | 提示词块，治角色数量对不上 |
| 地理空间布局 | GEO SPATIAL LAYOUT | 提示词块，治空间关系颠倒/越轴 |
| 动作时间线 | ACTION TIMING | 提示词块，逐秒动作 |
| 对白与音效 | AUDIO | 提示词块，台词只许出现在这里 |
| 角色表演 | CHARACTER ACTING | 提示词块，情绪/身体节奏 |
| 风格前缀 | STYLE | 提示词块，逐字粘贴 |
| 正向约束 | POSITIVE CONSTRAINTS | 提示词块，反向点名失败镜头 |
| 提示词块 | block | 方法论 7 大块之一 |
| 铁律 | rule | 方法论 10 条硬规则（见方法论标签页） |
| 剧本套用 | script adaptation | 把用户剧本按工程模板转成分镜 |
| 分场 | scene split | 按空行把剧本切段，识别「第X场/SCENE n/INT./EXT.」标题 |
| 模板循环 | template cycling | 第 i 场用 `templates[i % templates.length]`，故不同场模板不同 |
| 角色映射 | characterMap | Hell Grind 角色 → 用户角色，**追加括号标注**而非替换 |
| 原文直送 | verbatim prompt | 提交给 Provider 的提示词逐字符等于原文，不过优化器 |
| 成本确认 | cost confirmation | 第 5 阶段入口的 checkpoint，确认前零调用 |
| checkpoint | — | 流水线暂停点，需用户显式确认才继续 |
| 本批 | batch | 一次出片的分镜集合，上限 10 镜 |
| 全量出片 | production | > 10 镜时自动切批、逐批确认、断点续跑 |
| 台账 | ledger.json | 断点续跑的状态文件，**但裁决依据是磁盘** |
| 渲染清单 | renderManifest | 跨批次聚合的成片输入，上限 10000 条 |
| 收口 | converge | 全部批次完成且磁盘复核通过，产出 renderManifest |
| 原片回收 | download recycled | 下载 kit 分镜原作者的成片到本地 |
| 受控媒体根 | media root | `os.tmpdir()/film-engineering`，所有产物落点 |
| fail-closed | — | 校验失败即整体不可用，不返回部分数据 |
| 模型 | model | 分镜的 `model` 字段**仅展示**，实际出片用你配的默认视频 Provider |

---

## 附录 A：提示词方法论精读

> 数据源：`apps/desktop/electron/film-kit/prompt-doctrine.json`（zh/en 双语）与 `prompt-doctrine.zh.md`（完整方法论文档）。
> 这一章解释「为什么这套提示词要这么写」，帮你判断**哪些块可以自己改、哪些块一个字都不能动**。

### A.1 七大提示词块逐个拆解

#### A.1.1 `SCENE CONTEXT`（场景上下文）

> 以角色计数头开篇（如 `EXACT 3 CHARACTERS — NO DUPLICATES`），后接场景动作与角色行

**它解决什么**：AI 视频模型最常见的崩坏是**角色数量对不上**——你要 3 个人，它画 4 个；这一镜 2 个下一镜 3 个。

**怎么用**：以「EXACT N CHARACTERS — NO DUPLICATES」这类**硬计数声明**开头，然后才写场景里发生什么、谁在场。

**能不能改**：计数头可以按你的实际人数改，格式别改。这是全篇最该照抄的一行。

#### A.1.2 `GEO SPATIAL LAYOUT`（地理空间布局）

> 纯场景平面图（地标、左右、相机站位、180° 轴线），不含角色与动作；**每场锁定逐镜粘贴不变**

**它解决什么**：空间关系前后颠倒。A 镜里门在左、B 镜里门跑到右；或者角色无端端越轴（从镜头左侧变到右侧，观众会瞬间出戏）。

**三条纪律**（方法论原文强调）：
1. **只写空间，不写人和动作**——这一块是"地图"，不是"剧本"；
2. **整场锁定，逐镜一字不改地粘贴**——这是保持空间连续性的唯一办法；
3. **明确写出 180° 轴线**和相机站位，锁住越轴。

**能不能改**：**不能改**。这一块一旦在某一镜被"顺手优化"，整场的空间连续性就崩了。这也是为什么复制模式里它单独占一个 `GEO 布局` 选项。

#### A.1.3 `ACTION TIMING`（动作时间线）

> 0.0-2.0s 逐秒动作；镜头运动写进动作；INNER (unspoken) 内心独白；分阶段眨眼与微表情

**它解决什么**：动作糊成一团。模型不知道"5 秒里几秒发生什么"，于是把 5 秒的动作压成 1 秒，或者干脆只做前 0.5 秒然后静止。

**怎么用**：**逐秒写**。`0.0-0.8s …`、`0.8-1.5s …` 这样切。镜头运动（推、拉、摇）**写在动作里**而不是单开一段——分开写模型会丢掉其中一个。内心独白用 `INNER (unspoken)` 标记，表示不出声。

**能不能改**：可以按你的镜头时长改切分粒度（5 秒的镜头切成 5 段，10 秒的切成 10 段），但"逐秒"这个写法别改。

#### A.1.4 `AUDIO`（对白与音效）

> 台词只存在于 AUDIO 块；音色锁定描述符原样粘贴；写明混音（人声近麦、环境底噪、说话时压低）

**它解决什么**：台词被模型"翻译"成画面文字，或者角色音色每镜都不一样（同一个角色上一镜低沉下一镜尖细）。

**三条纪律**：
1. **台词只许出现在这一块**——别在 `CHARACTER ACTING` 或 `SCENE CONTEXT` 里重复写台词，否则模型会当成画面文字渲染出来；
2. **音色描述符原样粘贴**——「低沉、沙哑、语速慢」这类描述每镜逐字重复，不要精简成「他说话了」；
3. **写明混音关系**——人声近麦、环境底噪铺底、有人说话时底噪压低。

**能不能改**：台词内容随便改（这是你的剧情），但「音色描述符逐字粘贴」和「只在此块」两条别破。

#### A.1.5 `CHARACTER ACTING`（角色表演）

> 情绪状态 · 此刻所求 · 隐瞒之物 · 身体节奏 · 可见习惯 · 本镜变化；**核心行为段永不改变**

**它解决什么**：表演平淡。模型让角色全程一张脸，或者动作像提线木偶。

**六要素**（方法论给的固定框架）：
1. **情绪状态**——他现在什么心情
2. **此刻所求**——这个镜头里他想要什么
3. **隐瞒之物**——他不想让人知道什么（这一项最出戏）
4. **身体节奏**——他运动的习惯（急促/迟缓/一顿一顿）
5. **可见习惯**——别人能看到的小动作（摸口袋、舔嘴唇）
6. **本镜变化**——相比上一镜，状态怎么变了

**能不能改**：六要素可以增删，但「**核心行为段永不改变**」是铁的——角色的底层行为逻辑跨镜必须一致。

#### A.1.6 `STYLE`（风格前缀）

> 逐字粘贴（`Photoreal. NON-IP. 16:9. 12s. SFX only. NO CGI. Cinematic.`）

**它解决什么**：风格逐镜漂移——这一镜写实、下一镜插画风。

**能不能改**：**逐字粘贴**。这是最像"密码"的一段，改一个词都可能让风格跳变。要改就整段全改，且所有镜同步改。

> ⚠️ **注意这行的 `12s`**：随包数据里这行写的是 12 秒，但**实际出片时长由你在界面上选（5/8/10 秒）**，引擎按你选的换算帧数提交（见 7.7）。**以界面选择为准**，提示词里的数字不会被自动改写。

#### A.1.7 `POSITIVE CONSTRAINTS`（正向约束）

> 8K 细节、毛孔级皮肤、无抖动闪烁；计数物体以「是什么在画面中」表述；点名失败镜头长什么样

**它解决什么**：细节崩坏、闪烁、多余肢体、质感下降。

**两个技巧**（方法论原文）：
1. **计数物体要写成「是什么在画面中」**——不要写「3 个苹果」，写「三个红苹果摆在桌上」。前者是数量指令，后者是画面描述，后者模型执行得准得多；
2. **点名失败镜头长什么样**——正向地说"不要出现"模型容易忽略，反向地说"如果出现 X 就是废了"更容易被遵守。

**能不能改**：可以按你的项目加约束，格式随意。

### A.2 十条铁律

这十条是方法论的执行纪律，**与具体项目无关**。原文与解读：

| # | 铁律 | 原文 | 解读 |
|---|---|---|---|
| 1 | 素材先行 | 角色/场景/道具全部锁定并压力测试之前，不生成任何一个镜头 | 先把资产（图、参考图）定死，再开始出片。资产没锁定就出片 = 返工 |
| 2 | 每次全量描述 | 模型没有记忆，描述符逐字粘贴、永不缩写 | 别用「同上」「还是那样」。模型每次都是第一次见你 |
| 3 | 一次只改一处 | 整段重写会丢掉生效的部分；每次迭代记录日志 | 改一处 → 出片 → 看效果。一次改五处，出了新问题你不知道是哪处引起的 |
| 4 | 少给自由 | 角落而非房间、锚点而非空地、地图而非猜测、每镜一个动作 | 约束越具体，结果越可控。别给模型发挥空间 |
| 5 | 简化镜头不简化措辞 | 镜头不出来就简化镜头：拆成两镜、删一个动作、换角度；**10-15 次迭代上限** | 出不来不是你写得不够，是镜头太复杂。**并且有迭代预算上限**——超过 15 次就该换思路了 |
| 6 | 每场第一秒固定广角 | 无人声无动作，把站位/光线"拍"进模型 | 用一个安静的广角开场锁定空间，再切近景。这一条与 `GEO` 块配合使用 |
| 7 | 写肌肉不写形容词 | 颤抖、下颌咬紧、颧骨绷紧、鼻息；静止写成「绷住的张力」而非「别动」 | 形容词模型无法执行，身体细节可以。**「别动」是无效指令，「绷住的张力」是有效指令** |
| 8 | 音色是锁定描述符 | register/tempo/accent/manner 在 pre-production 锁定，逐次粘贴 | 音色要像角色定妆一样，在开拍前就定死 |
| 9 | 点修改用蒙版 | 衣服/伤疤/血在 Nano Banana 改后手工蒙版合回原图；**图片绝不全图二过模型** | 局部改动不要整图重生成——整图重跑会让没改的地方也漂移 |
| 10 | 台词只在 AUDIO 块 | 声音+情绪 → 引号台词 → 肢体动作 → 面部反应；无台词者完全沉默 | 见 A.1.4。**无台词的镜头要明确写"完全沉默"**，否则模型会自己加旁白 |

### A.3 术语表（数据自带）

| 术语 | 中文释义 | 用在哪 |
|---|---|---|
| `seedance_2_0` | 视频生成模型（剧情镜头主力） | 143/153 个分镜用它 |
| `nano_banana_2` | 图片生成模型（角色定妆/素材图） | 5 个分镜 |
| `soul_cinematic` | 电影感图片模型（氛围/质感图） | 3 个分镜 |
| `reference token` | 引用令牌：`<<<uuid>>>` 形式的资产引用，**逐字保留** | 见 4.4 |
| `character sheet` | 角色定妆三视图：面部特写 + 正面无头全身 + 背面全身 | 铁律 1「素材先行」的产物 |
| `GEO block` | 地理空间布局块（每场锁定，逐镜粘贴不变） | 见 A.1.2 |

> **注意**：`character sheet` 定义的「正面无头全身」（无头）是刻意的——避免模型给全身镜头编一张脸，导致与面部特写对不上。这是定妆三视图的标准做法。

### A.4 怎么用这套方法论（三种姿势）

| 姿势 | 怎么做 | 适合 |
|---|---|---|
| **原样复用** | 直接复制 kit 分镜的完整提示词，喂给你的 Provider | 想快速看效果；信任原片质量 |
| **换剧情** | 保留块结构与 GEO 块，把剧情句、台词、动作换成你的（这就是「剧本套用」在做的事） | 有自己的剧本，想套用方法 |
| **当模板学习** | 把方法论标签页的内容当写作规范，自己写提示词 | 长期做 AI 影视，想建立自己的方法论 |

> **我的建议**：从「原样复用」起步。先跑通 3~5 镜，确认你的 Provider 能吃这套结构，再考虑换剧情。一上来就改结构，你分不清是方法不对还是 Provider 不行。

---

## 附录 B：三个完整实战案例

> 三个案例覆盖三种典型需求。步骤按实际界面顺序写，括号内是文件依据。

### B.1 案例一：从零做一支 3 镜短片（画布路线）

**目标**：把自己的 3 场小剧本变成一支 3 镜成片。

**前置**：已登录；模型设置里配好并设为默认的视频 Provider。

| 步 | 操作 | 预期 | 依据 |
|---|---|---|---|
| 1 | 视频创作页 → 点「影视工程」卡片 | 进入画布（`/film-engineering`），显示空网格 + 左下缩放条 + 右下小地图 | 路由 `router/index.js:52` |
| 2 | 顶部剧本框粘贴 3 场剧本（**段间空行**，标题写「第1场/第2场/第3场」） | 下方提示「剧本最多 10000 字」 | `useFilmCanvas.js:21` |
| 3 | 顶部画幅选 `16:9 横屏`，时长选 `5 秒` | — | `FilmCanvasView.vue:151-156` |
| 4 | 点「拆分镜」 | 提示「已生成 3 个分镜」；画布上出现 3 个分镜节点（每行 4 个，所以排一行） | `film-canvas-model.js:64-93` |
| 5 | （可选）点「上传人物参考」选一张 PNG ≤10MB | 提示「参考图已添加」；画布下方出现一个参考节点 | `useFilmCanvas.js:116-159` |
| 6 | 从参考节点右侧连接点拖到分镜节点左侧 | 落一条线。**只连你要用这张参考的镜** | `film-canvas-model.js:29-35` |
| 7 | 选中这 3 个分镜节点 | — | `FilmCanvasView.vue:45-48` |
| 8 | 点「生成所选」 | 弹出成本确认卡「将为 3 个分镜生成视频，确认后才开始计费。」 | `FilmCanvasView.vue:202-208` |
| 9 | 点「确认成本并生成」 | 节点徽标依次变「生成中」→「已完成」 | `video-gen.js` 轮询 10s/次 |
| 10 | 右下角浮出绿色条「成片已生成」 | — | `FilmCanvasView.vue:211-216` |
| 11 | 点「另存为」存到你自己的目录 | **必做**——产物在系统临时目录会被清理 | 见 2.4 |

**成本**：3 镜 × 1 次视频生成 = 3 次计费调用（1 个 Provider 任务/镜）。

**避坑**：
- 第 7 步**一定要选中**。不选会生成全部节点——3 镜无所谓，但如果你画布上还有别的镜，就超预算了；
- 第 4 步之后如果发现提示词不是你想要的，**删掉重来**（点节点 × → 清空画布 → 重新填剧本），画布没有撤销。

### B.2 案例二：从原片分镜库批量出 5 镜（经典视图路线）

**目标**：从随包 kit 的 153 个分镜里挑 5 个，直接出片成片。

| 步 | 操作 | 预期 | 依据 |
|---|---|---|---|
| 1 | 进入画布 → 右上角点「经典视图」 | 跳到 `/film-engineering/classic` | `FilmCanvasView.vue:162` |
| 2 | 顶部确认 kit 状态卡正常（片名含「Hell Grind」） | 说明数据资产加载成功 | E2E `film-engineering-real.js:207` |
| 3 | 左侧场景树点任一场景 | 右侧加载该场景分镜，显示「已加载 N / 共 M 镜」 | — |
| 4 | 点某张分镜卡的**复制**按钮 | 提示「提示词已复制到剪贴板」——**先存一份原文备份** | — |
| 5 | 勾选 5 张分镜 | 工具栏按钮亮起 | — |
| 6 | 工具栏点「生成视频」 | 浮出视频生成面板（idle 态） | `FilmEngineeringView.vue:272-352` |
| 7 | 面板里选画幅 `16:9`、时长 `5 秒`，点「发起生成」 | **成本确认卡**出现，列出 5 行逐镜清单 | `video-gen.js:286-304` |
| 8 | **核对清单**（这一步别省） | 每行：镜序号 + shotId + 画幅 + 时长；确认 Provider 是你配的那个 | — |
| 9 | 点「确认生成」 | 逐镜状态回显 | — |
| 10 | 有失败镜 → 点「重试」 | 只重跑该镜，覆盖 `shot_00N.mp4`，**不重跑其他镜** | 见 8.4 |
| 11 | 全部成功 → 「成片已生成」→ 点「另存为」 | — | — |

**成本**：5 镜 = 5 次计费调用。

**避坑**：
- **第 8 步的 Provider 名字要核对**。分镜详情里显示的「模型」是原片用的（多为 seedance_2_0），但**实际出片用的是你配的默认 Provider**（见 2.2）。两者不一致是正常的，成本确认卡上显示的 Provider 才是真实计费对象；
- **第 4 步的原文备份建议做**。出片是原文直送，失败了重试还是原文——但如果你想改成别的写法，得自己手里有原文。

### B.3 案例三：全量出片 50 镜 + 中断续跑（长任务路线）

**目标**：出 50 镜，中途关掉应用，第二天接着跑。

| 步 | 操作 | 预期 | 依据 |
|---|---|---|---|
| 1 | 经典视图 → 分镜库 → 勾选 50 个分镜 | — | — |
| 2 | 工具栏点「全量出片」 | 浮出全量出片面板 | `FilmEngineeringView.vue:355-445` |
| 3 | 填任务 ID `my-film-01-20261007` | 只允许字母/数字/`.`/`_`/`-`，长度 1-64 | `ipc-handlers/film-engineering.js:63` |
| 4 | 点「发起出片」 | 出现**批次计划预览**：「共 5 批（每批最多 10 镜），本次 50 个分镜」+ 磁盘预估 400 MB + 耗时预估 4 小时 10 分 | 口径见 12.4 |
| 5 | **仔细读预估** | 数字太大就改小分镜数。这一步是唯一能在花钱前反悔的机会 | — |
| 6 | 点「确认执行本批」 | 第 0 批开始跑，进度实时回显「第 k/5 批」「N/M 镜」 | `production-driver.js:194-200` |
| 7 | 第 0 批跑完 | 出现第 1 批的确认卡；顶部显示「累计已确认 10 镜」 | — |
| 8 | 确认第 1 批 | — | — |
| 9 | **跑到第 2 批时，故意关掉应用** | — | — |
| 10 | 重新打开应用 → 经典视图 → 分镜库 → **重新勾选同样的 50 个分镜（顺序也要一样）** | — | 见下方避坑 |
| 11 | 点「全量出片」→ 填**同一个**任务 ID → 点「恢复任务」 | 台账视图出现：第 0、1 批「已完成」，第 2 批「待确认」 | `ipc-handlers/film-engineering.js:458-485` |
| 12 | 逐批继续确认 | 前 2 批被**跳过**（不花钱） | `production-driver.js:207-215` |
| 13 | 全部 5 批收口 | 提示「全部批次已收口，渲染清单共 50 条」+ 出现「合成成片」按钮 | — |
| 14 | 点「合成成片」 | 跨 5 个批次目录聚合成 `final.mp4`（零计费直通，不弹成本卡） | `video-gen.js:241-249` |
| 15 | 「成片已生成」→ 另存为 | — | — |

**成本**：50 镜 = 50 次计费调用（合成阶段不花钱）。

**避坑**：
- **第 10 步的 shotIds 顺序必须一致**。系统靠「批次结构是否与计划一致」判断能否续跑；不一致会**重建台账 = 从头再来**（`production-driver.js:178-185`）。这不是 bug——它无法知道你的新顺序是不是同一个任务；
- **第 13 步的收口是硬条件**。任何一批有缺失镜头，**不产出成片**（`暂无法合成：渲染清单未收口`）。想出片就得把缺的镜补齐（重试或回收）；
- **第 14 步不弹成本卡是正常的**。收口 run 的 `generate_videos` 阶段显式声明 `checkpoint: false`——它没有分镜要生成，零计费直通到合成（`video-gen.js:244-246`）。**不是成本闸被绕过**；
- 如果某些批失败了，**不影响其他批**。处理完失败镜、收口通过后照样能合成。

---

## 附录：文档信息

| 项 | 值 |
|---|---|
| 编写基线 | `main@8409afa`（2026-10-07） |
| 取证方式 | 逐文件阅读源码 + 数据资产实测 + 交叉验证 E2E 断言 |
| 数据资产实测 | `film-manifest.json` / `shot-library.json` / `reference-registry.json` / `prompt-doctrine.json` 全量统计 |
| 交叉验证 | 两轮独立只读调研复核（前端交互链路 / IPC 契约与入口注册），关键差异逐条回源码复核 |
| 已知差异汇总 | 第十四章（画布功能缺口 10 项 / 数据限制 6 项 / 策略不一致 1 项 / 元数据不一致 1 处 / 代码瑕疵 12 项） |
| 维护建议 | 流水线行为变更时同步更新 4.6（六阶段）、12.4（成本口径）、十四章（差异清单）三处 |

> **本手册的诚实边界**：凡标注「未实现」「未发现证据」处，均为对 `main@8409afa` 的实际代码 grep 与阅读结果，不是对规格文档的转述。规格承诺与实现不符时，**以实现为准**，差异全部登记在第十四章。
