const assert = require('assert')
const fs = require('fs')
const path = require('path')
const test = require('node:test')
const yaml = require('js-yaml')

test('生产监控配置可解析并覆盖关键身份依赖', () => {
  const directory = path.resolve(__dirname, '../../../deploy/logto/monitoring')
  const prometheus = yaml.load(fs.readFileSync(path.join(directory, 'prometheus.yml'), 'utf8'))
  const alerts = yaml.load(fs.readFileSync(path.join(directory, 'alerts.yml'), 'utf8'))
  const blackbox = yaml.load(fs.readFileSync(path.join(directory, 'blackbox.yml'), 'utf8'))
  const alertmanager = yaml.load(fs.readFileSync(path.join(directory, 'alertmanager.example.yml'), 'utf8'))
  const compose = yaml.load(fs.readFileSync(path.resolve(directory, '../docker-compose.monitoring.yml'), 'utf8'))

  const jobs = prometheus.scrape_configs.map((entry) => entry.job_name)
  assert(jobs.includes('multi-publish-api-ready'))
  assert(jobs.includes('logto-oidc-discovery'))
  assert.strictEqual(blackbox.modules.http_2xx.prober, 'http')

  const names = alerts.groups.flatMap((group) => group.rules.map((rule) => rule.alert))
  assert(names.includes('MultiPublishApiNotReady'))
  assert(names.includes('LogtoOidcUnavailable'))
  assert(names.includes('IdentityProbeSlow'))
  assert(names.includes('IdentityProbeMissing'))
  const missingRule = alerts.groups.flatMap((group) => group.rules).find((rule) => rule.alert === 'IdentityProbeMissing')
  assert.match(missingRule.expr, /absent\(probe_success/)
  assert.strictEqual(prometheus.alerting.alertmanagers[0].static_configs[0].targets[0], 'alertmanager:9093')
  assert.strictEqual(compose.services.alertmanager.image.startsWith('prom/alertmanager:'), true)
  assert.strictEqual(alertmanager.route.receiver, 'operations-webhook')
})
